### DISCUSSION TITLE
How to connect ftp folder as media directory?

### DISCUSSION THREAD

**Discussion by tequilaonelove** [AzuraCast/AzuraCast#3868] [Q&A]
Hello, on the server, using the curlftpfs 
`sudo curlftpfs -o allow_other ftp://user:password@ip/ /var/azuracast/stations/mystation/media` 
command, I connect the ftp server as a folder. Next, I create the docker-compose.override.yml file, in which I write:
```
version: '2.2'

services:
  web:
    volumes:
      - /var/azuracast/stations/mystation/media:/var/azuracast/stations/mystation/media/

  stations:
    volumes:
      - /var/azuracast/stations/mystation/media:/var/azuracast/stations/mystation/media/

```
and run `docker-compose down`, `docker-compose up -d` . 

But if the media file is successfully uploaded to the station, it is not visible either on the ftp server or on the local one. 
When connected to a docker container, the media files are in the path:  `/var/azuracast/stations/mystation/temp`. 
Is it possible to connect ftp server to azuracast?
