### DISCUSSION TITLE
Replace nginx configurations (example: increase port range) is not more possible

### DISCUSSION THREAD

**Discussion by youngdesenv** [AzuraCast/AzuraCast#4016] [Q&A]
**Using Docker installation method**
YES
**AzuraCast version**
0.12.2
**Host Operating System**
Ubuntu 20

Hi,

There was a way to override nginx settings in previous versions, but now in the current one when trying to upload the .nginx file using override.yml, error 502 occurs.

Is there any new way to do this?
(I use the version with docker)

**Comment by BusterNeece** [comment]
@youngdesenv You should now add custom configuration into a special directory, like so:

```yaml
version: '2.2'

services:
  web:
    volumes:
      - ./custom.conf:/etc/nginx/azuracast.conf.d/custom.conf
```

Any files ending in `.conf` in the `/etc/nginx/azuracast.conf.d` folder will automatically be included by the main AzuraCast nginx configuration.
