### DISCUSSION TITLE
Cover images upload issue

### DISCUSSION THREAD

**Discussion by pstvdy** [AzuraCast/AzuraCast#4745] [Q&A]
Hi,
after a recent update AzuraCast has cleared all cover images, also .albumart directory has vanished.
Now, when I try to upload an image I get the message 
"League\Flysystem\UnableToCreateDirectory at /var/azuracast/www/vendor/league/flysystem/src/UnableToCreateDirectory.php L20: Unable to create a directory at /var/azuracast/stations/media/.albumart. mkdir(): Permission denied"

Obviously I've checked the folders permissions and are right.
I think that the issue is due a mapping to a not correct path in docker-compose,override.yml

```
version: '2.2' 
services: 
  web: 
    volumes: - /mnt/volume_00/library/masters:/var/azuracast/stations/media/masters 

  stations: 
    volumes: - /mnt/volume_00/library/masters:/var/azuracast/stations/media/masters
```

The local storage in AzuraCast panel, related to the station, is "/var/azuracast/stations/media"

So I've the doubt that the redirecting of a subdirectory of media can create some issues.
All other functions of upload of music works well without issues.

Sorry for the question but I'm almost a newbie about AzuraCast environment and also I took over the technical management of a little web radio and I'm not the guy that has installed AzuraCast first time.
Thanks
