### DISCUSSION TITLE
Can I Add port 8054? please teach me how, thank you.

### DISCUSSION THREAD

**Discussion by 1017ylfm** [AzuraCast/AzuraCast#5719] [General]
Can I Add port 8054 on azuracast? please teach me how, thank you.

**Comment by ChrisDuffley** [comment]
You sure can! Paste the following into the file /var/azuracast/docker-compose.override.yml:

```
services:
  web:
    ports:
      - "8054:8054"
```
Then Ctrl+X in Nano to save. You'll be good after you do
```
docker compose down;docker compose up -d
```
while inside the AzuraCast directory.
