### DISCUSSION TITLE
How do i change Play Button Size in the latest AzuraCast versions?

### DISCUSSION THREAD

**Discussion by unudelaradio** [AzuraCast/AzuraCast#6719] [Q&A]
Hello!

In older versions i used this custom CSS for changing the color and size of play button.

.radio-control-play-button {color: #7453FC; font-size: 18px !important;}

Now, after the lastest updates, only the color is changing.

What CSS should i use for changing the play button size?

**Comment by BusterNeece** [comment]
Try targeting the icon directly:

```css
.radio-player-widget .radio-controls .radio-control-play-button .icon {
  font-size: 18px !important;
}
```
