### DISCUSSION TITLE
Directory exists but was not created by docker compose warning

### DISCUSSION THREAD

**Discussion by Sella-GH** [AzuraCast/AzuraCast#6766] [General]
Since we moved from one server to another (taking all volumes with us) we get this warnings for every volume every time we update the server.

I don't find the position where I have to insert the named parameter nor do I know how to get the warning away.

Someone already experienced this?

`WARN [00001 volume "azuracast_www_uploads" already exists but was not created by Docker Compose. Use 'external: true' to use an existing`

**Comment by vahidirp** [comment]
This warning message is related to a Docker Compose configuration and suggests that a volume named "azuracast_www_uploads" already exists, but Docker Compose did not create it. The message recommends using the 'external: true' option to inform Docker Compose that the volume is external and has been created outside of the current Docker Compose configuration.

In Docker Compose, volumes are used to persist data generated by containers. When defining a volume in a Docker Compose file, Docker Compose typically creates the volume if it doesn't exist. However, in this case, it seems like the volume "azuracast_www_uploads" is pre-existing and wasn't created by Docker Compose.

To resolve this issue and inform Docker Compose that the volume already exists externally, you can modify your Docker Compose file by adding the 'external: true' option to the volume definition. For example:

```
version: "3"
services:
  your_service:
    # Your service configuration here
volumes:
  azuracast_www_uploads:
    external: true
```

By specifying external: true, you're indicating that the volume should not be created by Docker Compose, and it should use the existing volume with the given name.

Make sure to replace "your_service" with the actual name of the service in your Docker Compose file that uses this volume.

This adjustment helps Docker Compose to understand that the volume is managed externally, preventing it from attempting to recreate an existing volume and eliminating the warning you encountered.

**Comment by Sella-GH** [comment]
Hello, thanks for trying to help at first.

I tried it with different approaches over the docker-compose.overwrite.yml (because we shouldn't modify the compose one) and it doesn't seem to work.
Maybe I'm doing something wrong with the content or the installer can't recognize what I really want.

Here's the file content, every help would be appreciated with this. 🙂

```
version: '3'

services:
  web:
    volumes:
      - 'station_data:/var/azuracast/stations'
      - 'backups:/var/azuracast/backups'
      - 'www_uploads:/var/azuracast/storage/uploads'
      - 'shoutcast2_install:/var/azuracast/storage/shoutcast2'
      - 'stereo_tool_install:/var/azuracast/storage/stereo_tool'
      - 'geolite_install:/var/azuracast/storage/geoip'
      - 'sftpgo_data:/var/azuracast/storage/sftpgo'
      - 'acme:/var/azuracast/storage/acme'

volumes:
  azuracast_station_data:
    external: true
  azuracast_backups:
    external: true
  azuracast_www_uploads:
    external: true
  azuracast_shoutcast2_install:
    external: true
  azuracast_stereo_tool_install:
    external: true
  azuracast_geolite_install:
    external: true
  azuracast_sftpgo_data:
    external: true
  azuracast_acme:
    external: true
```
