### DISCUSSION TITLE
Is it possible to change the error.mp3 file?

### DISCUSSION THREAD

**Discussion by houseofservers** [AzuraCast/AzuraCast#7493] [General]
Since I have a small home server where my azuracast is hosted, I have some sometimes server overload and/or blackouts in my area often so my listeners here the Azuracast audio... is it possible to change it to a standard one without mentioning "Free and Open Source" as it looks bad... I have created one as a sample...
[error.zip](https://github.com/user-attachments/files/17266744/error.zip)

**Comment by kcrpine** [comment]
I do believe there is a way to change it, cause I think there is a thing called custom error file in the administration of the station area I do believe.

**Comment by LordHelmchen666** [comment]
You could point to a custom file in docker-compose.override.yml
```
services:
    web:
        volumes:
            - /path/toyour/local/custom_error.mp3:/usr/local/share/icecast/web/error.mp3
```
