### DISCUSSION TITLE
Size / Album Artwork / Radio Player Widget for public pages

### DISCUSSION THREAD

**Discussion by DJDukeSr** [AzuraCast/AzuraCast#7531] [Q&A] [answered]
Someone help me getting  the "play button" bigger and added the command
 .radio-player-widget .radio-controls .radio-control-play-button .icon {
  font-size: 8.00rem; } 
I was happy that this works. 
Now I try to increase the album artwork, but when I increase the size, the play button gets smaller. Can someone add the command  for me ? Thanks in advance

**Comment by gAlleb** [comment, marked as answer]
```css
.radio-player-widget .now-playing-details .now-playing-art img {
  width: 150px;
  height: auto;
  border-radius: 10px;
}
```
