### DISCUSSION TITLE
Host AzuraCast with Traefik: Unable to migrate database

### DISCUSSION THREAD

**Discussion by brunolnetto** [AzuraCast/AzuraCast#7805] [Ideas]
Hi guys,

I tried hosting azuracast using Traefik instead of nginx. My rationale is to follow these instructions [1], and adequate to the procedure I want: 

1. Obtain file `docker-compose.yaml`; 
2. Copy+paste compose file available on environment files `.env` and `azuracast.env`;
3. Run command `docker stack deploy -c docker-compose.yaml azuracast `.

[1] https://www.azuracast.com/docs/administration/docker/

```
version: "3.7"

services:
  azuracast:
    image: "ghcr.io/azuracast/azuracast:latest"
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "com.centurylinklabs.watchtower.scope=azuracast"
        - "traefik.enable=true"
        - "traefik.http.routers.azuracast.rule=Host(`radio.example.com`)"
        - "traefik.http.routers.azuracast.entrypoints=websecure"
        - "traefik.http.routers.azuracast.tls.certresolver=letsencrypt"
        - "traefik.http.middlewares.azuracast-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.azuracast.middlewares=azuracast-https-redirect"
        - "traefik.http.services.azuracast.loadbalancer.server.port=80"
    depends_on:
      - azuracast_db
      - azuracast_redis
      - azuracast_influxdb
    networks:
      - mynetwork
    volumes:
      - azuracast_tmp:/tmp/azuracast
      - azuracast_logs:/var/azuracast
      - azuracast_station_data:/var/lib/azuracast/stations
      - azuracast_uploads:/var/azuracast/storage/uploads      
      - azuracast_backups:/var/azuracast/backups
      - azuracast_shoutcast2:/var/azuracast/storage/shoutcast2
      - azuracast_stereo_tool:/var/azuracast/storage/stereo_tool
      - azuracast_rsas:/var/azuracast/storage/rsas
      - azuracast_geolite:/var/azuracast/storage/geoip
      - azuracast_sftpgo:/var/azuracast/storage/sftpgo
      - azuracast_acme:/var/azuracast/storage/acme

    environment:
      - SHOW_DETAILED_ERRORS=true
      - COMPOSER_PLUGIN_MODE=true
      - AUTO_ASSIGN_PORT_MIN=8000
      - AUTO_ASSIGN_PORT_MAX=8499
      - SHOW_DETAILED_ERRORS=false

      - ENABLE_DATABASE=true
      - MYSQL_HOST=azuracast_db
      - MYSQL_DATABASE=azuracast
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azura_pass
      - MYSQL_SSL=false
      - MYSQL_SSL_MODE=disabled
      - MYSQL_CLIENT_SSL=false
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

      - ENABLE_REDIS=true
      - REDIS_HOST=azuracast_redis
      
      - INFLUXDB_HOST=azuracast_influxdb
      
      - AZURACAST_DB_HOST=azuracast_db
      - AZURACAST_REDIS_HOST=azuracast_redis

      - PUID=1000
      - PGID=1000
      
      - TZ=America/Sao_Paulo

  updater:
        container_name: azuracast_updater
        image: 'ghcr.io/azuracast/updater:latest'
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        logging:
            options:
                max-size: 1m
                max-file: '5'

  azuracast_db:
    image: mariadb:10.11
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - mynetwork
    volumes:
      - azuracast_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=azuracast
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azura_pass

  azuracast_redis:
    image: redis:6
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - mynetwork
    volumes:
      - azuracast_redis:/data

  azuracast_influxdb:
    image: influxdb:1.8
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - mynetwork
    volumes:
      - azuracast_influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=stations

networks:
  mynetwork:
    external: true

volumes:
  azuracast_tmp: {  }  
  azuracast_logs: {  }
  azuracast_station_data: {  }
  azuracast_uploads: {  }
  azuracast_backups: {  }
  azuracast_shoutcast2: {  }
  azuracast_stereo_tool: {  }
  azuracast_rsas: {  }
  azuracast_geolite: {  }
  azuracast_sftpgo: {  }
  azuracast_acme: {  }

  azuracast_db: {  }
  azuracast_redis: {  }
  azuracast_influxdb: {  }
```

```
Database Migrations

===================

 [OK] Metadata storage synchronized                                             

Backing up initial database state...

------------------------------------

 [INFO] We detected a database restore file from a previous (possibly failed)   

        migration.                                                              

                                                                                

        Attempting to restore that now...                                       

ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it

 [ERROR] The command "mariadb --user=$DB_USERNAME --password=$DB_PASSWORD       

         --host=$DB_HOST --port=$DB_PORT $DB_DATABASE < $DB_DUMP" failed.       

                                                                                

         Exit Code: 1(General error)                                            

                                                                                

         Working directory: /var/azuracast/backups                              

                                                                                

         Output:                                                                

         ================                                                       

                                                                                

                                                                                

         Error Output:                                                          

         ================                                                       

         ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does

         not support it                                                         

Generating Database Proxy Classes

---------------------------------

 Processing entity "App\Entity\Settings"

 Processing entity "App\Entity\SongHistory"

 Processing entity "App\Entity\StorageLocation"

 Processing entity "App\Entity\StationMedia"

 Processing entity "App\Entity\UnprocessableMedia"

 Processing entity "App\Entity\PodcastMedia"

 Processing entity "App\Entity\StationMediaCustomField"

 Processing entity "App\Entity\StationHlsStream"

 Processing entity "App\Entity\CustomField"

 Processing entity "App\Entity\StationWebhook"

 Processing entity "App\Entity\StationRemote"

 Processing entity "App\Entity\StationStreamer"

 Processing entity "App\Entity\Podcast"

 Processing entity "App\Entity\StationSchedule"

 Processing entity "App\Entity\ApiKey"

 Processing entity "App\Entity\User"

 Processing entity "App\Entity\StationPlaylist"

 Processing entity "App\Entity\Role"

 Processing entity "App\Entity\StationQueue"

 Processing entity "App\Entity\Relay"

 Processing entity "App\Entity\StationPlaylistMedia"

 Processing entity "App\Entity\StationMount"

 Processing entity "App\Entity\StationPlaylistFolder"

 Processing entity "App\Entity\UserPasskey"

 Processing entity "App\Entity\RolePermission"

 Processing entity "App\Entity\UserLoginToken"

 Processing entity "App\Entity\SftpUser"

 Processing entity "App\Entity\AuditLog"

 Processing entity "App\Entity\PodcastCategory"

 Processing entity "App\Entity\Station"

 Processing entity "App\Entity\Listener"

 Processing entity "App\Entity\StationStreamerBroadcast"

 Processing entity "App\Entity\Analytics"

 Processing entity "App\Entity\PodcastEpisode"

 Processing entity "App\Entity\StationRequest"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data

------------------

[2025-03-23T14:27:48.845557+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 40 while running console command `azuracast:setup` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:40)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:24)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:57)"} []

[2025-03-23T14:27:48.849151+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1146. [] []

In ExceptionConverter.php line 40:

                                                                               

  An exception occurred while executing a query: SQLSTATE[42S02]: Base table   

  or view not found: 1146 Table 'azuracast.settings' doesn't exist             

                                                                               

In Exception.php line 24:

                                                                               

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  

  gs' doesn't exist                                                            

                                                                               

In Connection.php line 57:

                                                                               

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  

  gs' doesn't exist                                                            

                                                                               

azuracast:setup [--update] [--load-fixtures] [--release] [--init]

2025-03-23 11:27:49,889 WARN exited: startup (exit status 1; not expected)
```
