### ISSUE TITLE
Azuracast behind letsencrypt-nginx-proxy-companion

### ISSUE THREAD

**Issue by aldorr** [AzuraCast/AzuraCast#1170]
**Is your feature request related to a problem? Please describe.**
Filing under Feature Request, because it is not necessarily something AzuraCast purports to support, but it did work in v1.

I have multiple containers running alongside AzuraCast. These are all behind an nginx proxy, which serves the correct container based on the URL requested. (see [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)). This worked fine if I disabled AzuraCast's built in Let's Encrypt, until v2 came out. Now I can not get AzuraCast to start liquidsoap and broadcast.
The following error appears:
` NO_FILE: can't find command '/var/azuracast/.opam/system/bin/liquidsoap' `

It seems similar to [this issue at first glance](https://github.com/AzuraCast/AzuraCast/issues/963) issue, but self-updating and updating - then updating the docker-compose.yml to defer to my nginx proxy... doesn't cut it. (Well, probably because of the last step for my proxy.)

**Describe the solution you'd like**
I'd like to be able to change some settings in the docker-compose.yml to easily use my own certificates and have AzuraCast work with my current server configuration again. (It's fine if I have to do it manually each time. I just can't seem to figure out how to get it up and running again.)

**Describe alternatives you've considered**
I've thought about running AzuraCast on a separate physical server, which would mean extra costs, and possibly other configuration headaches.

**Additional context**
Here's what I tried in my docker-compose.yml
Behind the proxy, I have to use _expose_ instead of _ports_
and add the container to my nginx-proxy network.
```
# AzuraCast Docker Compose Configuration File

version: '2.2'

services:
  web:
    image: azuracast/azuracast_web_v2:latest
    expose:
      - 80
      - 443
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    env_file: azuracast.env
    environment: &default-environment
      AZURACAST_DC_REVISION: 5
    volumes:
      # - letsencrypt:/etc/letsencrypt
      - /var/lib/docker/volumes/dockernginxproxy_certs/_data:/etc/nginx/ssl
      - www_data:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
    environment:
      VIRTUAL_HOST: url.net
      LETSENCRYPT_HOST: url.net
      LETSENCRYPT_EMAIL: me@url.net
    restart: always
    logging: &default-logging
      options:
        max-size: "1m"
        max-file: "5"

  mariadb:
    image: azuracast/azuracast_db:latest
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    env_file: azuracast.env
    environment:
      <<: *default-environment
    restart: always
    logging: *default-logging

  influxdb:
    image: azuracast/azuracast_influxdb:latest
    volumes:
      - influx_data:/var/lib/influxdb
    expose:
      - 8086
    restart: always
    logging: *default-logging

  redis:
    image: azuracast/azuracast_redis:latest
    expose:
      - 6379
    restart: always
    logging: *default-logging

  stations:
    container_name: azuracast_stations
    image: azuracast/azuracast_radio:latest
    expose:
    # - '8000-8500'
     - 8000
     - 8005
     - 8006
     - 8010
     - 8015
     - 8016
     - 8020
     - 8025
     - 8026
     - 8030
     - 8035
     - 8036
     - 8040
     - 8045
     - 8046
     - 8050
     - 8055
     - 8056
     - 8060
     - 8065
     - 8066
     - 8070
     - 8075
     - 8076
     - 8090
     - 8095
     - 8096
    volumes:
     - station_data:/var/azuracast/stations
     - shoutcast2_install:/var/azuracast/servers/shoutcast2
     - /var/lib/docker/volumes/dockernginxproxy_certs/_data/:/etc/nginx/ssl:ro
     # - letsencrypt:/etc/nginx/ssl:ro
    init: true
    restart: always
    logging: *default-logging

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  db_data: {}
  influx_data: {}
  # letsencrypt: {}
  shoutcast2_install: {}
  station_data: {}
  tmp_data: {}
  www_data: {}
```

Thanks for any tips or suggestions!
