### ISSUE TITLE
sctrans2 implentation and ftp access for each station.

### ISSUE THREAD

**Issue by dzsam** [AzuraCast/AzuraCast#1258]
Hi,
Everyone appreciates Liquidsoap, I agree with that, but for my part, I don't appreciate how it makes the transition ( cross-fading) between the live stream and autoDJ.
The cut is dry.
There may be a way to create a cross-fading for this situation, but I don't know it.
that's why I continue to use sctrans2 with shoutcast2, the cross-fading between live streaming and autoDj is excellent.
So it would be nice if it was possible to add sctans2
Ading an ftp server:
Adding an ftp access automatically to each new station . would also be nice
the ftp account will be the name of the radio, and the password will be the admin account.
Best regards
Samy

**Comment by Vaalyn** [comment]
If you are using the docker installation you can easily add an SFTP server to your radio stack by creating a `docker-compose.override.yml` with this as content:

```
version: '2.2'

services:
    sftp:
        container_name: azuracast_sftp
        image: atmoz/sftp:alpine
        ports:
            - '2222:22'
        volumes:
            - /var/lib/docker/volumes/azuracast_station_data/_data/<your-station>/media/:/home/azuracast_sftp
        restart: always
        command: <username>:<password>:1000
```

When adding this you may want to mount your own keys into the container in order to prevent unkown host errors when the container restarts and generates new keys.

Add these mounts to the `volumes:`

```
- ./ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
- ./ssh/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub
- ./ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
- ./ssh/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub
```
