### ISSUE TITLE
Access to edit entire Liquidsoap config? 

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1751]
Would it be possible to somehow edit the the entire Liquidsoap config not just the part under "Advanced Custom Conifguration"? Right now the only way is to change the settings on the admin website but we'd need direct access to the file, be able to edit it and restart the server. 

Background: due to some long running issues with the Liquidsoap config (e.g., https://github.com/savonet/liquidsoap/issues/746) we'd like to help with experimenting. Maybe we can find a good scripting, which can then be merged in a future version of AzuraCast.

**Comment by Vaalyn** [comment]
It's not something that I'd recommend for production but for those experiments you can use the `docker-compose.override.yml` to mount your custom liquidsoap config file over the existing one in read-only mode. That way AzuraCast can't overwrite the file and you can experiment with it.

**Comment by gammaw** [comment]
@Vaalyn thanks. It seems that I managed to mount a custom LS config with the following override file. Just like you suggested. I can see changes to the file in the logs view of the Azuracast admin page. But I see no effects of it. First of all, Azuracast doesn't detect the changes (doesn't want me to restart the backend). And when I restart the "Auto DJ Service", Azuracast won't apply the changes to the file, it will restart with the original Liquidsoap config instead. Do you know how I could force Azuracast to load the edited config file?  

```
services:
  web:
    volumes:
      - ./liquidsoap_custom.liq:/var/azuracast/stations/devlahma/config/liquidsoap.liq 
```

**Comment by Vaalyn** [comment]
That's most likely happening because your custom file is mounted as read/write. You need to mount it as read-only so that AzuraCast can't generate a new one.

You can do this by adding `:ro` at the end of the line:
```
services:
  web:
    volumes:
      - ./liquidsoap_custom.liq:/var/azuracast/stations/blaradio/config/liquidsoap.liq:ro
```
