### ISSUE TITLE
Rebuild Liquidsoap Adding Plugins

### ISSUE THREAD

**Issue by Azoto1985** [AzuraCast/AzuraCast#1943]
Hi, is there a way to recompile Liquidsoap from docker  in order to add some plugins?

I need to add those plugins:

libgstreamer1.0-0 gstreamer1.0-plugins-base \
   gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good \
   gstreamer1.0-plugins-bad gstreamer1.0-tools gstreamer1.0-libav

Thanks in advance

**Comment by SlvrEagle23** [comment]
@Azoto1985 You can always build your own custom Docker image that pulls from ours. Your Dockerfile could start with:

```
FROM azuracast/azuracast_radio:latest
```

and then you can create a `docker-compose.override.yml` file that tells the `stations` container to use that new image:

```yaml
version: '2.2'

services:
  stations:
    image: my_custom_radio:latest
    build:
      context: .
```
