### ISSUE TITLE
Proper format of docker-compose,override.yml file

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#1994]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

Current File (modified by Buster)
version: '2.2'
services:
web:
  volumes:
    - /var/azuracast/stations:/var/azuracast/stations
    - /var/azuracast/backups:/var/azuracast/backups
stations:
  volumes:
    - /var/azuracast/stations:/var/azuracast/stations
  ports:
    - '8100-8500:8100-8500'

**Additional context**

services:
  stations:
      volumes:
          - /var/azuracast/www/silentintro.mp3:/usr/local/share/icecast/web/error.mp3

*** /var/azuracast/www/silentintro.mp3    is the location and name of the file I wish to use.
I am unsure about the format of that string and where in the file to place it.
I've have indentation and format issues in the past with this file which only leads to stations going offline and bad things happening.
Would appreciate someone showing the proper formatting for this statement/file.

Thanks as always!

**Comment by SlvrEagle23** [comment]
@williambatson So, you merge the two as if they're creating one single YAML definition, like so:

```yaml
version: '2.2'
services:
  web:
    volumes:
    - /var/azuracast/stations:/var/azuracast/stations
    - /var/azuracast/backups:/var/azuracast/backups
  stations:
    volumes:
    - /var/azuracast/stations:/var/azuracast/stations
    - /var/azuracast/www/silentintro.mp3:/usr/local/share/icecast/web/error.mp3
  ports:
    - '8100-8500:8100-8500'
```
