### ISSUE TITLE
docker-compose.override.yml does not overrride

### ISSUE THREAD

**Issue by Nuube** [AzuraCast/AzuraCast#2261]
I tried to change the station ports using  docker-compose.override.yml because some of the ports listed there are already in use on my server. 

```
version: '2.2'

services:
  stations:
    ports:
      - "18500-18999:18500-18999"
```

The ports indicaded here are just added, but the one from docker-compose.yml are still used in the container which eventually leads to the container does not start.

`Error starting userland proxy: listen tcp 0.0.0.0:8200: bind: address already in use`
