### ISSUE TITLE
Ansible traditional update script issue

### ISSUE THREAD

**Issue by replayfactory** [AzuraCast/AzuraCast#2298]
**Using Docker installation method**
No

**Host Operating System**
Ubuntu 18.04

**Issue**

Hi There :-)
Looks like there is an error with ansible script wich updating a traditional install.
The symlink to liquidsoap located in `/usr/local/bin` does not include azuracast app_base folder

File : `~azuracast/www/util/ansible/roles/azuracast-radio/tasks/main.yml`

Relevant code : 
```
- name: Link Liquidsoap binary
    file:
      src: /var/azuracast/.opam/4.08.0/bin/liquidsoap
      dest: /usr/local/bin/liquidsoap
      state: link
      force: yes
```

**Comment by SlvrEagle23** [comment]
@replayfactory This is by design; `/usr/local/bin` is already in the Ubuntu 16.04 default PATH.

The idea with the Ansible installer isn't to contain everything inside the AzuraCast installation directory; it's actually installing packages at the system level and making modifications well outside its normal base directory.

**Comment by replayfactory** [comment]
@SlvrEagle23 I probably misspoke. After upgrading, liquidsoap couldn't start anymore because `/usr/local/bin/liquidsoap` refers to an nonexistent file.

In my case, the path to liquidsoap is `{{ app_base }}/.opam/4.08.0/bin/liquidsoap`

```
- name: Link Liquidsoap binary
    file:
      src: {{ app_base }}/.opam/4.08.0/bin/liquidsoap
      dest: /usr/local/bin/liquidsoap
      state: link
      force: yes
```
