### ISSUE TITLE
SFTP Port not applied

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#2335]
**Using Docker installation method**
Docker yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
I update today to the latest version of Azuracast wich include SFTP server, put port on azuracast.env and here my docker-compose and env file: 
```
AZURACAST_SFTP_PORT=2222
```
```
  web:
    container_name: azuracast_web
    image: azuracast/azuracast_web_v2:latest
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    env_file: azuracast.env
    ports:
      - '${AZURACAST_HTTP_PORT:-80}:80'
      - '${AZURACAST_HTTPS_PORT:-443}:443'
      - '${AZURACAST_SFTP_PORT:-2022}:2022'
    environment: &default-environment
      AZURACAST_DC_REVISION: 7
      LANG: ${LANG:-en_US.UTF-8}
    volumes:
      - www_data:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - geolite_install:/var/azuracast/geoip
      - sftpgo_data:/var/azuracast/sftpgo/persist
      - /home/valentin/azuracast/stations/:/var/azuracast/stations
      - /home/valentin/azuracast/shoutcast2_install:/var/azuracast/servers/shoutcast2
      - /home/valentin/azuracast/backups:/var/azuracast/backups
    restart: always
    logging: &default-logging
      options:
        max-size: "10m"
        max-file: "5"
```

**To Reproduce**
Type `docker ps -a` -> Port bind on 2022 not 2222

Thanks
