### ISSUE TITLE
using web interface behind reverse proxy breaks requests

### ISSUE THREAD

**Issue by joshms123** [AzuraCast/AzuraCast#2436]
**Using Docker installation method**

Yes.
**Host Operating System**

Debian.
**Describe the bug**
I am using the azuracast web interface behind the traefik reverse proxy. However, it seems that azuracast is not getting the forwarded IP from the client. This causes the request system to rate limit a client, even though they haven't requested anything.

**To Reproduce**
Use the azuracast web interface (:80 :443) behind the traefik reverse proxy.

**Expected behavior**
The correct IP to be rate limited.

**Relevant Logs**

**Screenshots**

**Device(s):**
Windows 10, Chrome.
**Additional context**
Is it possible to alter the rate limiting?

**Comment by joshms123** [comment]
Followup - the azuracast nginx container doesn't seem to be forwarding the treafik IP to azuracast. Instead, it is using the 172 docker container internal network IP.

**Comment by AlexTeusz** [comment]
Hi,

are there any news on this topic? I want to install azuracast as well as a docker service behind my traefik reverse proxy. I am getting a bad gateway with the following setting in my `radio.yml` file:

```yml
  web:
    ....
    deploy:
      restart_policy:
        condition: any
      labels:
        traefik.frontend.rule: 'Host:radio.domain.de'
        traefik.enable: 'true'
        traefik.port: '2022'
        traefik.docker.network: frontend
    networks:
      - frontend
...
```

Thank you for your help!
