### ISSUE TITLE
SSL working on Icecast but not on the Backend (Nginx)

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#2541]
This issue follow this previous one https://github.com/AzuraCast/AzuraCast/issues/1193

**Using Docker installation method**
Yes

**Host Operating System**
 Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-76-generic x86_64)

**Describe the bug**
This is a long-time problem and I thought it would have been fixed overtime but I realized it may come from the way I configure Azuracast. 

I'm using Azuracast with docker in an already LAMP configured VPS and I already have the SSL certificates  automatically generated for the domain used. I can manage to make them work with Icecast following this process, but can't do it with the web server. 
How is it possible ? Also, how could I make the Icecast SSL process automatic instead of it everytime manually when I update Azuracast ?

**To Reproduce**

Here is the .env file
```
COMPOSE_PROJECT_NAME=azuracast

AZURACAST_HTTP_PORT=8088
AZURACAST_HTTPS_PORT=444
```

Here is the content of the docker-compose.override.yml file

```
version: '2.2'

services:
  web:
    volumes:
      - /media/airtime-nfs/azuracast:/mnt/chezyouhoo
      - /home/admin/conf/web/:/var/azuracast/ssl

  stations:
    volumes:
      - /media/airtime-nfs/azuracast:/mnt/chezyouhoo
      - /home/admin/conf/web/:/var/azuracast/ssl
```

in terminal :
```
./docker.sh update-self && echo "y" | ./docker.sh update (update azuracast)
docker exec -it azuracast_web /bin/bash (get in azuracast docker)
```
When in the azuracast docker: 
```
mkdir /etc/nginx/ssl
ln -sf /var/azuracast/ssl/ssl.myserver.org.crt /etc/nginx/ssl/ssl.crt
ln -sf /var/azuracast/ssl/ssl.myserver.org.key /etc/nginx/ssl/ssl.key
chmod 777 /etc/nginx/ssl/ssl.crt
chmod 777 /etc/nginx/ssl/ssl.key
```

Then I log in the web and restart Icecast, the Icecast feed (on port 8095) works in ssl 
http://myserver:8088/ > restart Icecast > https://myserver.org:8095/radio.mp3

When I try to browse https://myserver.org:8088/, I got this error 
**Error code: SSL_ERROR_RX_RECORD_TOO_LONG**

Please note that the server hosting the docker has a LAMP configuration with NGINX using this configuration/ports on the same domain (myserver.org)

myserver.org.nginx.conf
```
server {
    listen      myip:80;
    server_name myserver.org www.myserver.org basquecountry.myserver.org berlin.myserver.org hongkong.myserver.org marseille.myserver.org paris.myserver.org shop.myserver.org telaviv.myserver.org lausanne.myserver.org press.myserver.org mail.myserver.org label.myserver.org;
    error_log  /var/log/httpd/domains/myserver.org.error.log error;
    return 301 https://$host$request_uri;

    location / {
        proxy_pass      http://myip:8080;
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|tif|tiff|css|js|htm|html|ttf|otf|webp|woff|txt|csv|rtf|doc|docx|xls|xlsx|ppt|pptx|odf|odp|ods|odt|pdf|psd|ai|eot|eps|ps|zip|tar|tgz|gz|rar|bz2|7z|aac|m4a|mp3|mp4|ogg|wav|wma|3gp|avi|flv|m4v|mkv|mov|mpeg|mpg|wmv|exe|iso|dmg|swf)$ {
            root           /home/admin/web/myserver.org/public_html;
            access_log     /var/log/httpd/domains/myserver.org.log combined;
            access_log     /var/log/httpd/domains/myserver.org.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }

    location /error/ {
        alias   /home/admin/web/myserver.org/document_errors/;
    }

    location @fallback {
        proxy_pass      http://myip:8080;
    }

    include /home/admin/conf/web/nginx.myserver.org.conf*;
}
```

myserver.org.nginx.ssl.conf
```
server {
    listen      myip:443 http2;
    server_name myserver.org www.myserver.org ;
    ssl         on;
    ssl_certificate      /home/admin/conf/web/ssl.myserver.org.pem;
    ssl_certificate_key  /home/admin/conf/web/ssl.myserver.org.key;
    error_log  /var/log/httpd/domains/myserver.org.error.log error;

    location / {
        proxy_pass      https://myip:8443;
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|tif|tiff|css|js|htm|html|ttf|otf|webp|woff|txt|csv|rtf|doc|docx|xls|xlsx|ppt|pptx|odf|odp|ods|odt|pdf|psd|ai|eot|eps|ps|zip|tar|tgz|gz|rar|bz2|7z|aac|m4a|mp3|mp4|ogg|wav|wma|3gp|avi|flv|m4v|mkv|mov|mpeg|mpg|wmv|exe|iso|dmg|swf)$ {
            root           /home/admin/web/myserver.org/public_html;
            access_log     /var/log/httpd/domains/myserver.org.log combined;
            access_log     /var/log/httpd/domains/myserver.org.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }

    location /error/ {
        alias   /home/admin/web/myserver.org/document_errors/;
    }

    location @fallback {
        proxy_pass      https://myip:8443;
    }
```

**Expected behavior**
Be able to access to https://myserver:8088/ without error and with the original generated ssl certificate from the server hosting the docker azuracast image.

**Relevant Logs**
**Error code: SSL_ERROR_RX_RECORD_TOO_LONG** (when trying to access to the backend in https on firefox)

**Device(s):**
 - Device: Desktop / Phone 
 - OS: Windows 10
 - Browser: Firefox / Chrome
 - Version: Azuracast 0.9.9

**Additional context**
The SSL certificate is working well and is generated automatically by LetsEncrypt via VestaCP on the main server.

On the main server, checking the ports:
```
root@myserver:/media/airtime-nfs/azuracast/Playlist# sudo lsof -i:444
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
docker-pr 24547 root    4u  IPv6 87244690      0t0  TCP *:snpp (LISTEN)
root@myserver:/media/airtime-nfs/azuracast/Playlist# sudo lsof -i:8088
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
docker-pr 24568 root    4u  IPv6 87245226      0t0  TCP *:omniorb (LISTEN)
```

Thanks in advance!

**Comment by rubensben** [comment]
Should I change something in the azuracast.env in order to use another port than 443 for ssl in the docker configuration ? Like AZURACAST_HTTPS_PORT=another available port ?

I just can't test so much as the radio is in production.

**Comment by SlvrEagle23** [comment]
@rubensben You should probably be mapping the LetsEncrypt cert directly into its destination path inside Docker, as your symlinking is only taking effect _after_ nginx has already started:

```yaml
version: '2.2'

services:
  web:
    volumes:
      - /home/admin/conf/web/ssl.myserver.org.crt:/etc/nginx/ssl/ssl.crt:ro
      - /home/admin/conf/web/ssl.myserver.org.key:/etc/nginx/ssl/ssl.key:ro
      - /media/airtime-nfs/azuracast:/mnt/chezyouhoo

  stations:
    volumes:
      - /home/admin/conf/web/ssl.myserver.org.crt:/etc/nginx/ssl/ssl.crt:ro
      - /home/admin/conf/web/ssl.myserver.org.key:/etc/nginx/ssl/ssl.key:ro
      - /media/airtime-nfs/azuracast:/mnt/chezyouhoo
```
