### ISSUE TITLE
How install LetsEncrypt?

### ISSUE THREAD

**Issue by Berttas** [AzuraCast/AzuraCast#264]
How install LetsEncrypt SSL ? i use install method 1...

**Comment by Gartral** [comment]
I'd like to know how to install ANY SSL cert for azuracast.

**Comment by SlvrEagle23** [comment]
All AzuraCast instances will serve their web interface via both ports 80 and 443, with 443 using a self-signed certificate by default. You can then use a reverse proxy service like CloudFlare to provide a fully secure radio station for your listeners.

The reason SSL isn't necessarily a "first-class citizen" in AzuraCast has to do with its upstream components: both Icecast and Shoutcast don't easily or intuitively support SSL, and historically this has meant that the only way to listen to a radio station over a fully secure connection was to proxy the connection via nginx. AzuraCast does this as part of its default configuration, forwarding URLs in the form of `/radio/8000/stream.mp3` to `localhost:8000/stream.mp3`.

If you're using the traditional installer, you can supply your own SSL certificates by directly updating the nginx configuration at `/etc/nginx/sites-enabled/00-azuracast`. Replace the self-signed SSL cert path with the path of your own, restart nginx, and you'll be up and running.

If you're using Docker, you can you can alter the built-in `docker-compose.yml` file to map its configuration files to a custom path on your host, where you can then override the SSL settings. Assuming you create a path like `/var/azuracast/nginx` to store your local config, you can update your Docker Compose file to look something like:

```
version: '2'

services:
  nginx:
    image: azuracast/azuracast_nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
      - stations
    volumes:
      - .:/var/azuracast/www
      - /var/azuracast/nginx/azuracast.conf:/etc/nginx/conf.d/azuracast.conf
      - /var/azuracast/nginx/ssl/:/etc/nginx/ssl
    restart: always
```
