### ISSUE TITLE
Wrong listener IPs

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#2838]
I changed my docker-compose.override.yml to store station data on host server.
```
version: '2.2'

services:
  web:
    volumes:
      - /home/azuracast/backups:/var/azuracast/backups
      - /home/azuracast/stations:/var/azuracast/stations

  stations:
    volumes:
     - /home/azuracast/stations:/var/azuracast/stations
```

Now i get wrong IPs in listener stats like this.

```
192.168.32.6 | 1678 | desktop_windows Desktop-Gerät                             VLC/3.0.9.2 LibVLC/3.0.9.2 | Internal/Reserved IP
192.168.32.6 | 180 | desktop_windows Desktop-Gerät                             Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 | Internal/Reserved IP
192.168.48.6 | 166 | desktop_windows Desktop-Gerät                             VLC/3.0.9.2 LibVLC/3.0.9.2 | Internal/Reserved IP
192.168.64.6 | 1698 | desktop_windows Desktop-Gerät                             VLC/3.0.9.2 LibVLC/3.0.9.2 | Internal/Reserved IP
192.168.64.6 | 555 | desktop_windows Desktop-Gerät                             Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 | Internal/Reserved IP
192.168.64.6 | 29 | desktop_windows Desktop-Gerät                             okhttp/3.9.0 | Internal/Reserved IP

```

Web Proxy is enabled.

EDIT: Maybe same problem here https://github.com/AzuraCast/AzuraCast/issues/2821
