### ISSUE TITLE
Installation instructions / CLI

### ISSUE THREAD

**Issue by danbo** [AzuraCast/AzuraCast#285]
Brand new test.. since I have docker, I went straight to
```
docker-compose pull
docker-compose run --rm cli azuracast_install
docker-compose up -d
```
and upon running the second line, I got
```
# docker-compose run --rm cli azuracast_install
Starting azuracast_redis_1 ...
Starting azuracast_influxdb_1 ... done
Starting azuracast_stations ... done
Starting azuracast_web_1 ... done
Updating AzuraCast (Environment: production)
ERROR! the playbook: util/ansible/docker_install.yml could not be found
```

.. was able to fix this by adding the www folder / volume for the cli service in the compose file, so from

```
cli:
    image: azuracast/azuracast_web:latest
    volumes_from:
      - web
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    user: 'azuracast'
    working_dir: '/var/azuracast/www'
    command: 'bash'
```
to 
```
cli:
    image: azuracast/azuracast_web:latest
    volumes_from:
      - web
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    user: 'azuracast'
    working_dir: '/var/azuracast/www'
    command: 'bash'
    volumes:
      - .:/var/azuracast/www
```
