### ISSUE TITLE
Nginx Config

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#2891]
**Using Docker installation method**
YES

**AzuraCast version**
v0.10.2, #954b4d7 (2020-05-23 1:28) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**

Where is the nginx.conf file located.I want to make some changes there.
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by suricloud** [comment]
Please let know where  to edit this file.Need to setup a proxy for another app on the same server.

**Comment by costellogary** [comment]
Hey, I found it at this path:
AzuraCast/util/docker/web/nginx/nginx.conf

**Comment by SlvrEagle23** [comment]
@suricloud You can map custom configuration to the `nginx_proxy` service via something like this in your `docker-compose.override.yml`:

```
version: '2.2'

services:
  nginx_proxy:
    volumes:
     - /my/nginx.conf:/etc/nginx/vhost.d/mydomain.example.com.conf
```

...where "mydomain.example.com" is the domain for whichever container's configuration you want to update (meaning your AzuraCast config if that's what you're updating).
