### ISSUE TITLE
Public Page/Index.phtml Not Displaying

### ISSUE THREAD

**Issue by buddhatunes** [AzuraCast/AzuraCast#2959]
Looking for guidance on where to customize the public page. In v.0.9.8 I successfully customized index.phml at:

/var/lib/docker/volumes/azuracast_www_data/_data/templates/frontend/public/index.phtml

I made a copy of index.phtml, upgraded to v.0.10.2, uploaded the copy, but my customizations do not appear anymore even though I see them in index.phtml at the above location.

Ubuntu 20.04
v0.10.2, #9a956b4
Docker: yes

**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@buddhatunes It's definitely a better idea to mount the modified file via Docker Compose, not directly modifying the filesystem to make those changes.

For example, you'd have a `docker-compose.override.yml` file with these contents:

```
version: '2.2'

services:
  web:
    volumes:
      ./index.phtml:/var/azuracast/www/templates/frontend/public/index.phtml
```
