### ISSUE TITLE
500 Database Error while Setup Register

### ISSUE THREAD

**Issue by AlexTeusz** [AzuraCast/AzuraCast#2973]
**Using Docker installation method**

yes

**AzuraCast version**

latest

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

I installed AzuraCast via docker on my server and installed it behind my traefik reverse proxy server. Thus, I did not include the ngnix images azuracast provde. 

After starting the azuracast stack, I am able to visit the page under https://radio.domain.de while I get an error after inserting my new user information in the `/setup/register` path.

I get the following error message: 
```
500

An exception occurred while executing 'INSERT INTO audit_log (timestamp, operation, class, identifier, target_class, target, changes, user) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [1592577405, 1, "Role", "Super-Administrator", null, null, "a:1:{s:4:\"name\";a:2:{i:0;N;i:1;s:19:\"Super-Administrator\";}}", null]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.audit_log' doesn't exist
AbstractMySQLDriver.php : 42 
```

**To Reproduce**

Please contact me private via teusz.alexander[at]gmail.com so that I can show you my server setup.

**Expected behavior**

**Relevant Logs**

**Screenshots**

![Screenshot of the problem](https://alexteusz.s3-eu-west-1.amazonaws.com/Bildschirmfoto+2020-06-19+um+16.42.01.png)

**Device(s):**
 - Device:  
 - OS: 
MAC OSX, Linux Server
 - Browser: 
Google Chrome
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@AlexTeusz Did you encounter any errors during the setup process? It seems your database migrations may not have run for some reason.

You can try to resolve this by running an update:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

**Comment by AlexTeusz** [comment]
I think my self-created docker stack is not working together with the databases. This is my stack file:

```yml
version: "3.5"

services:
  # nginx_proxy:
  #   image: "azuracast/azuracast_nginx_proxy:${AZURACAST_VERSION:-latest}"
  #   volumes:
  #     - letsencrypt:/etc/nginx/certs
  #     - nginx_proxy_vhosts:/etc/nginx/vhost.d
  #     - letsencrypt_html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   environment:
  #     DEFAULT_HOST: ${LETSENCRYPT_HOST:-azuracast.local}
  #   depends_on:
  #     - web
  #   deploy:
  #     restart_policy:
  #       condition: any
  #     labels:
  #       traefik.frontend.rule: 'Host:radio.domain.de'
  #       traefik.enable: 'true'
  #       traefik.port: '80'
  #       traefik.docker.network: frontend

  web:
    image: "azuracast/azuracast_web_v2:${AZURACAST_VERSION:-latest}"
    # Want to customize the HTTP/S ports? Follow the instructions here:
    # https://www.azuracast.com/help/docker/#use-non-standard-ports
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    ports:
      - '${AZURACAST_SFTP_PORT:-2022}:2022'
    env_file: azuracast.env
    environment:
      LANG: ${LANG:-en_US.UTF-8}
      AZURACAST_DC_REVISION: 9
      AZURACAST_VERSION: ${AZURACAST_VERSION:-latest}
      AZURACAST_SFTP_PORT: ${AZURACAST_SFTP_PORT:-2022}
      VIRTUAL_HOST: ${LETSENCRYPT_HOST:-azuracast.local}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - geolite_install:/var/azuracast/geoip
      - sftpgo_data:/var/azuracast/sftpgo/persist
      - backups:/var/azuracast/backups
    deploy:
      restart_policy:
        condition: any
      labels:
        traefik.frontend.rule: 'Host:radio.alexteusz.de'
        traefik.enable: 'true'
        traefik.port: '80'
        traefik.docker.network: frontend
    networks:
      - frontend
      - database

  mariadb:
    image: "azuracast/azuracast_db:${AZURACAST_VERSION:-latest}"
    volumes:
      - db_data:/var/lib/mysql
    env_file: azuracast.env
    deploy:
      restart_policy:
        condition: any
    networks:
      - database
      - frontend

  influxdb:
    image: "azuracast/azuracast_influxdb:${AZURACAST_VERSION:-latest}"
    volumes:
      - influx_data:/var/lib/influxdb
    deploy:
      restart_policy:
        condition: any
    networks:
      - database
      - frontend

  redis:
    image: "azuracast/azuracast_redis:${AZURACAST_VERSION:-latest}"
    deploy:
      restart_policy:
        condition: any
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - redis_data:/data
    networks:
      - database
      - frontend

  stations:
    image: "azuracast/azuracast_radio:${AZURACAST_VERSION:-latest}"
    ports:
      # This default mapping is the outgoing and incoming ports for the first 50 stations.
      # You can override this port mapping in your own docker-compose.override.yml file.
      # For instructions, see:
      # https://www.azuracast.com/help/docker/#expand-the-docker-radio-station-port-range
      - '8000:8000'
     ...
      - '8496:8496'
    volumes:
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - letsencrypt:/etc/nginx/ssl:ro
      - tmp_data:/var/azuracast/www_tmp
    deploy:
      restart_policy:
        condition: any
    networks:
      - database
      - frontend

# before starting the stack, this network has to be installed: 
# - docker network create --attachable --driver overlay frontend
# - docker network create --driver overlay --attachable --opt encrypted=true database
# the services network
networks: 
  frontend:
    external: true
  database:
    external: true

volumes:
  nginx_proxy_vhosts: 
    external: true
  db_data: 
    external: true
  influx_data:
    external: true
  letsencrypt:
    external: true
  letsencrypt_html:
    external: true
  shoutcast2_install:
    external: true
  geolite_install:
    external: true
  sftpgo_data:
    external: true
  station_data:
    external: true
  tmp_data:
    external: true
  redis_data:
    external: true
  backups:
    external: true
```

So the reverse proxy seems to work so that the webpage is available.
