### ISSUE TITLE
Public Page

### ISSUE THREAD

**Issue by nickloud** [AzuraCast/AzuraCast#3023]
Hello. How to replace a picture on a public page? there used to be a folder and just could be replaced. Now I can not find this folder

**Comment by SlvrEagle23** [comment]
@nickloud On the custom branding page, you can add something like this to the Custom CSS for Public Pages field:

```css
body.page-minimal {
  background-image: url('https://i.imgur.com/1YGODry.jpg');
}
```
