### ISSUE TITLE
IceCast not using SSL certificate on fresh install

### ISSUE THREAD

**Issue by esmondgh** [AzuraCast/AzuraCast#3204]
Using Docker installation method:
**Yes**

Host Operating System:
**Ubuntu 18.04**

AzuraCast Version:
**0.10.3**

**Description:**
After a fresh Installation of AzuraCast, I found below warning In /var/lib/docker/volumes/azuracast_station_data/_data/station_name/config/icecast.log

[2020-09-09  04:06:44] WARN xml/parsing warning: 
[2020-09-09  04:06:44] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2020-09-09  04:06:44] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)
[2020-09-09  04:06:44] WARN slave/slave_startup process has 65536 max file descriptor limit

**Working: https://my-stream-url/radio/8000/stream.mp3
Not Working: https://my-stream-url:8000/stream.mp3**

**Question**
Is It possible to mount my own SSL certificate in "docker-compose.override.yml" to use by IceCast for radio streams?.

**Comment by esmondgh** [comment]
After updating to **AzuraCast v0.10.4**, the warning above has changed to below.

[2020-10-02  09:07:39] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2020-10-02  09:07:39] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/certs/mydomain.com.crt (PEM lib)
[2020-10-02  09:07:39] WARN slave/slave_startup process has 65536 max file descriptor limit

**Please note that I have mounted the SSL certificate in "docker-compose.override.yml"**

**Working: https://my-stream-url/radio/8000/stream.mp3
Not Working: https://my-stream-url:8000/stream.mp3**

**Comment by Vaalyn** [comment]
When mounting your own SSL certificate make sure to follow the instructions under `Using Custom Certificates` in this issue: https://github.com/AzuraCast/AzuraCast/issues/2855

The documentation on the AzuraCast website has not yet been updated to reflect that change. I'll submit a PR for that.

**Comment by esmondgh** [comment]
**1. My IceCast config contains the following configuration:**
```
<ssl-private-key>/etc/nginx/certs/example.com.key</ssl-private-key>
<ssl-certificate>/etc/nginx/certs/example.crt</ssl-certificate>
```

**2. I have mounted my own SSL certificate like below:**
version: '2.2'

services:
  nginx_proxy:
    volumes:
      - /path/on/host/to/ssl.crt:/etc/nginx/certs/yourdomain.com.crt:ro
      - /path/on/host/to/ssl.key:/etc/nginx/certs/yourdomain.com.key:ro

**3. The SSL certificate is mounted correctly because the web connection is using it.**

**4. IceCast is able to find the SSL certificates, but the warning is showing Invalid cert file.**
[2020-10-02 09:07:39] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2020-10-02 09:07:39] WARN connection/get_ssl_certificate **Invalid cert file** /etc/nginx/certs/mydomain.com.crt (PEM lib)
[2020-10-02 09:07:39] WARN slave/slave_startup process has 65536 max file descriptor limit

**Comment by Vaalyn** [comment]
Add the following to your docker-composer.override.yml (don't forget to replace `yourdomain.com` with your domain) to mount the custom cert into the stations container so that IceCast has access to it:

```
stations:
    volumes:
      - /path/on/host/to/ssl.crt:/etc/nginx/certs/yourdomain.com.crt:ro
      - /path/on/host/to/ssl.key:/etc/nginx/certs/yourdomain.com.key:ro
```

So that you have it like this:
```
version: '2.2'

services:
    nginx_proxy:
        volumes:
            - /path/on/host/to/ssl.crt:/etc/nginx/certs/yourdomain.com.crt:ro
            - /path/on/host/to/ssl.key:/etc/nginx/certs/yourdomain.com.key:ro

    stations:
        volumes:
            - /path/on/host/to/ssl.crt:/etc/nginx/certs/yourdomain.com.crt:ro
            - /path/on/host/to/ssl.key:/etc/nginx/certs/yourdomain.com.key:ro
```
