### ISSUE TITLE
Can not use custom azuracast.conf

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#3902]
**Using Docker installation method**

Yes

**AzuraCast version**

 Rolling Release #9af25b3 (2021-03-09 8:49) 

**Host Operating System**

Ubuntu 20.4

**Describe the bug**

I have custom ports so I am required to modify the azuracast.conf file as well.

my docker-compose.override.yml file:
```yaml

`version: '2.2'

services:
  web:
    volumes:
     - /var/azuracast/azuracast-nginx.conf:/etc/nginx/conf.d/azuracast.conf:ro

  stations:
    ports:
      - "6060-6062:6060-6062"
      - "8000-8500:8000-8500"
 
```
If I do not use RO, it replaces the local file that overrides all the settings I changed.

```

web_1                      | Starting up AzuraCast services...
web_1                      | Services started up and ready!
web_1                      | *** Running /etc/my_init.d/nginx.sh...
web_1                      | 2021/03/09 22:32:44 unable to create open /etc/nginx/conf.d/azuracast.conf: read-only file system
web_1                      | *** /etc/my_init.d/nginx.sh failed with status 1
web_1                      |
web_1                      | *** Killing all processes...
```
I'm not sure but maybe it's related, because it's been happening since I updated.

https://github.com/AzuraCast/AzuraCast/blob/61be661f558d01cd1936fec5150cc33693e81f8a/util/docker/web/startup_scripts/nginx.sh#L4

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@YosefAdPro If you have custom nginx rules, you can still include them by mounting them to a directory like:

```yaml
version: '2.2'

services:
  web:
    volumes:
     - /var/azuracast/azuracast-nginx.conf:/etc/nginx/azuracast.conf.d/custom.conf:ro
```

The main `azuracast.conf` file includes any files that are in `/etc/nginx/azuracast.conf.d` which can be mounted without worrying about any template being overwritten.
