### ISSUE TITLE
Can't enabling HTTPS with a Custom Certificate

### ISSUE THREAD

**Issue by Ferz0id** [AzuraCast/AzuraCast#4334]
**Using Docker installation method?**
Yes 
**AzuraCast version:**
v0.13.0 Stable
**Host Operating System:**
Ubuntu 16.04

Can't install custom SSL Certificate in my configuration. Please help me understand what I'm doing wrong

**Steps to reproduce the behavior:**
1.	First I got 4 certificate files for my site via LetsEncrypt:

> cert.pem
> chain.pem
> fullchain.pem
> privkey.pem

HTTPS for my site works fine

2.	Then I convert this files to key/cert format via OpenSSL:
```
openssl rsa -in privkey.pem -out edmdnb.com.key
openssl crl2pkcs7 -nocrl -certfile fullchain.pem | openssl pkcs7 -print_certs -out edmdnb.com.crt
```
3.	Then I create docker-compose.override.yml file:
 ```
version: '2.2'

services:
  nginx_proxy:
    volumes:
      - /etc/letsencrypt/live/edmdnb.com/edmdnb.com.crt:/etc/nginx/certs/edmdnb.com.crt:ro
      - /etc/letsencrypt/live/edmdnb.com/edmdnb.com.key:/etc/nginx/certs/edmdnb.com.key:ro

  stations:
    volumes:
      - /etc/letsencrypt/live/edmdnb.com/edmdnb.com.crt:/etc/nginx/certs/edmdnb.com.crt:ro
      - /etc/letsencrypt/live/edmdnb.com/edmdnb.com.key:/etc/nginx/certs/edmdnb.com.key:ro
```
4. HTTPS for Azuracast still does not work with errors:

SSL_ERROR_RX_RECORD_TOO_LONG
MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT
