### ISSUE TITLE
Listeners page returns incorrect data - Internal/Reserve IP location

### ISSUE THREAD

**Issue by simpsss** [AzuraCast/AzuraCast#5002]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#dcea1b9

### What happened?

After the last update (#dcea1b9), is not showing the real IPs and locations of the people who are listening.

Maybe it's because you changed the nginx proxy?

![image](https://user-images.githubusercontent.com/51731449/150011494-c81a0de7-7d7a-4d5a-89a3-6561666f91f1.png)

**Comment by SC2Mitch** [comment]
Shall check in a moment, standby.

**Comment by dvdred** [comment]
> I have the same issue on my installation on docker, version #fcdc50c
I don't know why, but i solved the issue in this way:
- docker-compose down of azuracast
- update and reboot of the docker host (CenOS 7)
- docker-compose up of azuracast (with the same version: #fcdc50c)
Now i can see the public ip of the listeners.

**Comment by SlvrEagle23** [comment]
I suspect this may be indeed caused by our retirement of the multi-container nginx proxy solution, but it should be fixed after updating.

Some possible causes of problems may be:
 - Do you have a `docker-compose.override.yml` file? Make sure that's updated to not have any references to `nginx_proxy` or `nginx_proxy_letsencrypt_companion` (unless you're actually using a multi-site configuration)
 - Make sure when updating that you run `./docker.sh update-self` first, to ensure the updater is running all the necessary steps

**Comment by SC2Mitch** [comment]
Updated to latest rolling, and still retains the Internal IP
![image](https://user-images.githubusercontent.com/29955942/150539654-8c284c77-10e7-4f5e-99e6-a4a29dd18a93.png)

Not using a override file.

**Comment by SlvrEagle23** [comment]
@SC2Mitch And just to confirm, there's no `nginx_proxy` service listed in the main `docker-compose.yml` file?

**Comment by SC2Mitch** [comment]
Nope, this is my main file for clarity
```
services:
    web:
        container_name: azuracast_web
        image: 'ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}'
        ports:
            - '${AZURACAST_HTTP_PORT:-80}:80'
            - '${AZURACAST_HTTPS_PORT:-443}:443'
            - '${AZURACAST_SFTP_PORT:-2022}:2022'
        depends_on:
            - mariadb
            - stations
            - redis
        env_file: azuracast.env
        environment:
            LANG: '${LANG:-en_US.UTF-8}'
            AZURACAST_DC_REVISION: 13
            AZURACAST_VERSION: '${AZURACAST_VERSION:-latest}'
            AZURACAST_SFTP_PORT: '${AZURACAST_SFTP_PORT:-2022}'
            NGINX_TIMEOUT: '${NGINX_TIMEOUT:-1800}'
            LETSENCRYPT_HOST: '${LETSENCRYPT_HOST:-}'
            LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:-}'
            PUID: '${AZURACAST_PUID:-1000}'
            PGID: '${AZURACAST_PGID:-1000}'
        volumes:
            - 'letsencrypt:/etc/nginx/certs'
            - 'letsencrypt_internal:/etc/acme.sh'
            - 'www_vendor:/var/azuracast/www/vendor'
            - 'www_uploads:/var/azuracast/uploads'
            - 'tmp_data:/var/azuracast/www_tmp'
            - 'station_data:/var/azuracast/stations'
            - 'shoutcast2_install:/var/azuracast/servers/shoutcast2'
            - 'geolite_install:/var/azuracast/geoip'
            - 'sftpgo_data:/var/azuracast/sftpgo/persist'
            - 'backups:/var/azuracast/backups'
        networks:
            - frontend
            - backend
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        logging:
            options:
                max-size: 1m
                max-file: '5'
    mariadb:
        container_name: azuracast_mariadb
        image: 'ghcr.io/azuracast/db:${AZURACAST_VERSION:-latest}'
        volumes:
            - 'db_data:/var/lib/mysql'
        env_file: azuracast.env
        networks:
            - backend
        restart: unless-stopped
        logging:
            options:
                max-size: 1m
                max-file: '5'
    redis:
        container_name: azuracast_redis
        image: 'ghcr.io/azuracast/redis:${AZURACAST_VERSION:-latest}'
        sysctls:
            net.core.somaxconn: 1024
        volumes:
            - 'redis_data:/data'
        networks:
            - backend
        restart: unless-stopped
        logging:
            options:
                max-size: 1m
                max-file: '5'
    stations:
        container_name: azuracast_stations
        image: 'ghcr.io/azuracast/radio:${AZURACAST_VERSION:-latest}'
        environment:
            PUID: '${AZURACAST_PUID:-1000}'
            PGID: '${AZURACAST_PGID:-1000}'
        ports:
            - '8000:8000' - I snipped the ports to save your eyes
        volumes:
            - 'station_data:/var/azuracast/stations'
            - 'shoutcast2_install:/var/azuracast/servers/shoutcast2'
            - 'letsencrypt:/etc/nginx/certs'
            - 'tmp_data:/var/azuracast/www_tmp'
        networks:
            - frontend
            - backend
        init: true
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        logging:
            options:
                max-size: 1m
                max-file: '5'
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    db_data: {  }
    letsencrypt: {  }
    letsencrypt_internal: {  }
    shoutcast2_install: {  }
    geolite_install: {  }
    sftpgo_data: {  }
    station_data: {  }
    www_vendor: {  }
    www_uploads: {  }
    tmp_data: {  }
    redis_data: {  }
    backups: {  }
```
