### ISSUE TITLE
Post installation station error from custom docker-compose

### ISSUE THREAD

**Issue by taz1685** [AzuraCast/AzuraCast#5335]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2

### What happened?

I managed to install AzuraCast via a custom docker-compose using the azuracast/azuracast_web_v2 image, as shown below (the main reason here is to deploy this into an existing server which has other docker environments running, so I did not want to use the installer to modify the host file system).

There are no problem is the setup and I am able to perform all the post instllation steps in getting the server operational. The problem I am facing starts, when trying to get the created station started. The following error is shown on the GUI when trying to start the station;

- "_TransportException at /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/TransportException.php L35: Transport error occurred: cURL error 6: Could not resolve host: stations (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:9001/RPC2_"

I am assuming this error is showing up since im using a custom install of AzuraCast, but it would be good to have the option or atleast understand what is needed to be modified to accomplish this type of deployment, I imaging there are many other people who are in the same boat, i.e. wanting to deploy a full stack directly by a docker-compose file rather then having to run a shell installer which deploy's the docker environment.

Any help will be great :)

_### Custom docker-compose_
```
services:
  azuracast:
    image: azuracast/azuracast_web_v2:0.15.2
    container_name: azuracast
    depends_on:
      - redis
      - mariadb
    restart: unless-stopped
    environment:
      LANG: en_US.UTF-8
      MYSQL_DATABASE: azuracast
      MYSQL_HOST: mariadb
      MYSQL_PASSWORD: azur4c457
      MYSQL_PORT: 3306
      MYSQL_USER: azuracast
      REDIS_DB: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: UTC
      PUID: 1000
      PGID: 1000
    volumes:
      - azuracast-www_tmp:/var/azuracast/www_tmp
      - azuracast-backups:/var/azuracast/backups
      - azuracast-sftpgo_persist:/var/azuracast/sftpgo/persist
      - azuracast-uploads:/var/azuracast/uploads
      - azuracast-nginx_certs:/etc/nginx/certs
    networks:
      default:
        ipv4_address: 10.10.1.15
      backend:
  redis:
    image: redis:6.2-alpine
    container_name: redis.internal
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis-data:/data
    networks:
      - backend
  mariadb:
    image: mariadb:10.6
    container_name: mariadb.internal
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=azuracast
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azur4c457
    volumes:
    - mariadb-data:/var/lib/mysql
    networks:
     - backend

volumes:
  azuracast-www_tmp:
    driver: local
  azuracast-backups:
    driver: local
  azuracast-sftpgo_persist:
    driver: local
  azuracast-uploads:
    driver: local
  azuracast-nginx_certs:
    driver: local
  redis-data:
    driver: local
  mariadb-data:
    driver: local
networks:
  default:
    external:
      name: DockerHostingNet
  backend:
    internal: true
```

### Relevant log output

```shell
[2022-05-02T00:00:19.355538+00:00] AzuraCast.ERROR: HTTP client GET call to http://stations:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"Default"}}
[2022-05-02T00:00:19.356931+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 28: Resolving timed out after 3000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8000/admin/stats [] {"station":{"id":1,"name":"Default"}}
```

**Comment by taz1685** [comment]
For brevity, here is are the logs as AzuraCast was going through its first init up untill the playlist for the Default station was created;
```
Starting up AzuraCast services...
🖥️🎶－🎵－📻 Waiting...🖥️－🎶－🎵📻 Waiting...🖥️🎵－🎶－📻 Waiting...🖥️－🎵－🎶📻 Waiting...🖥️🎶－🎵－📻 Waiting...🖥️－🎶－🎵📻 Waiting...Services started up and ready!
*** Running /etc/my_init.d/00_setup_user.sh...
usermod: no changes
Docker 'azuracast' User UID: 1000
Docker 'azuracast' User GID: 1000
*** Running /etc/my_init.d/01_self_signed_ssl.sh...
Generating self-signed certificate...
Generating a RSA private key
...................................................................+++++
......+++++
writing new private key to '/etc/nginx/certs/default.key'
-----
*** Running /etc/my_init.d/02_php.sh...
2022/05/02 08:32:11 Command finished successfully.
*** Running /etc/my_init.d/10_clear_temp.sh...
*** Running /etc/my_init.d/15_initialize.sh...
+ exec sudo -E -u azuracast azuracast_cli azuracast:setup:initialize

Initialize AzuraCast
====================

Initializing essential settings...
 * Environment: Production
 * Installation Method: Docker


Running Database Migrations
---------------------------



Generating Database Proxy Classes
---------------------------------


 Processing entity "App\Entity\StorageLocation"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\Podcast"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\Relay"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\StationRequest"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationQueue"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\PodcastEpisode"
 Processing entity "App\Entity\PodcastCategory"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\User"
 Processing entity "App\Entity\StationSchedule"
 Processing entity "App\Entity\UserLoginToken"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\StationStreamerBroadcast"
 Processing entity "App\Entity\UnprocessableMedia"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\PodcastMedia"
 Processing entity "App\Entity\Settings"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\Station"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data
------------------


                                                                                
 [OK] Local cache flushed.                                                      
                                                                                


                                                                                
 [OK] AzuraCast is now initialized.                                             
                                                                                

*** Booting runit daemon...
*** Runit started as PID 43
Spinning up Beanstalkd process...
Spinning up SFTP process...
Sleep for 3600s
[02-May-2022 08:32:21] NOTICE: fpm is running, pid 61
[02-May-2022 08:32:21] NOTICE: ready to handle connections
[02-May-2022 08:32:21] NOTICE: systemd monitor interval set to 10000ms
nginx: [warn] could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size
2022/05/02 08:32:21 [alert] 76#76: setrlimit(RLIMIT_NOFILE, 65000) failed (1: Operation not permitted)
2022/05/02 08:32:21 [alert] 79#79: setrlimit(RLIMIT_NOFILE, 65000) failed (1: Operation not permitted)
2022/05/02 08:32:21 [alert] 77#77: setrlimit(RLIMIT_NOFILE, 65000) failed (1: Operation not permitted)
2022/05/02 08:32:21 [alert] 78#78: setrlimit(RLIMIT_NOFILE, 65000) failed (1: Operation not permitted)
[2022-05-01T22:32:22.175861+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
{"level":"info","time":"2022-05-02T08:32:22.516","sender":"service","message":"starting SFTPGo 2.2.2-a792150-2022-02-06T14:12:25Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: /var/azuracast/sftpgo, config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, log utc time: false, load data from: \"\""}
{"level":"debug","time":"2022-05-02T08:32:22.519","sender":"config","message":"config file used: '\"/var/azuracast/sftpgo/sftpgo.json\"', config loaded: {Common:{IdleTimeout:15 UploadMode:2 Actions:{ExecuteOn:[upload pre-delete rename] ExecuteSync:[] Hook:/usr/local/bin/azuracast_sftp_event} SetstatMode:1 TempPath: ProxyProtocol:0 ProxyAllowed:[] StartupHook: PostConnectHook: PostDisconnectHook: DataRetentionHook: MaxTotalConnections:0 MaxPerHostConnections:20 DefenderConfig:{Enabled:false Driver:memory BanTime:30 BanTimeIncrement:50 Threshold:15 ScoreInvalid:2 ScoreValid:1 ScoreLimitExceeded:3 ObservationTime:30 EntriesSoftLimit:100 EntriesHardLimit:150 SafeListFile: BlockListFile:} RateLimitersConfig:[{Average:0 Period:1000 Burst:1 Type:2 Protocols:[SSH FTP DAV HTTP] AllowList:[] GenerateDefenderEvents:false EntriesSoftLimit:100 EntriesHardLimit:150}] idleTimeoutAsDuration:0 idleLoginTimeout:0 defender:<nil>} SFTPD:{Banner:SFTPGo_2.2.2 Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] MaxAuthTries:0 Actions:{ExecuteOn:[] ExecuteSync:[] Hook:} HostKeys:[persist/id_rsa persist/id_ecdsa persist/id_ed25519] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveAuthentication:false KeyboardInteractiveHook: PasswordAuthentication:true FolderPrefix: certChecker:<nil> parsedUserCAKeys:[]} FTPD:{Bindings:[{Address: Port:0 ApplyProxyConfig:true TLSMode:0 ForcePassiveIP: PassiveIPOverrides:[] ClientAuthType:0 TLSCipherSuites:[] PassiveConnectionsSecurity:0 ActiveConnectionsSecurity:0 Debug:false ciphers:[]}] Banner:SFTPGo 2.2.2 ready BannerFile: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] ActiveTransfersPortNon20:true DisableActiveMode:false EnableSite:false HASHSupport:0 CombineSupport:0 PassivePortRange:{Start:50000 End:50100}} WebDAVD:{Bindings:[{Address: Port:0 EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] Prefix: ProxyAllowed:[] allowHeadersFrom:[]}] CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0} Cache:{Users:{ExpirationTime:0 MaxSize:50} MimeTypes:{Enabled:true MaxSize:1000}}} ProviderConf:{Driver:bolt Name:sftpgo.db Host: Port:0 Username: Password:[redacted] SSLMode:0 ConnectionString: SQLTablesPrefix: TrackQuota:1 PoolSize:0 UsersBaseDir:/var/azuracast/stations Actions:{ExecuteOn:[] ExecuteFor:[] Hook:} ExternalAuthHook:/usr/local/bin/azuracast_sftp_auth ExternalAuthScope:0 CredentialsPath:credentials PreLoginHook: PostLoginHook: PostLoginScope:0 CheckPasswordHook: CheckPasswordScope:0 UpdateMode:0 PasswordHashing:{BcryptOptions:{Cost:10} Argon2Options:{Memory:65536 Iterations:1 Parallelism:2} Algo:bcrypt} PreferDatabaseCredentials:false SkipNaturalKeysValidation:false PasswordValidation:{Admins:{MinEntropy:0} Users:{MinEntropy:0}} PasswordCaching:true DelayedQuotaUpdate:0 CreateDefaultAdmin:false IsShared:0} HTTPDConfig:{Bindings:[{Address:127.0.0.1 Port:0 EnableWebAdmin:true EnableWebClient:true EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[] ProxyAllowed:[] HideLoginURL:0 RenderOpenAPI:true WebClientIntegrations:[] allowHeadersFrom:[]}] TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:backups OpenAPIPath:openapi WebRoot: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] SigningPassphrase:[redacted] MaxUploadFileSize:1048576000 Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0}} HTTPConfig:{Timeout:20 RetryWaitMin:2 RetryWaitMax:30 RetryMax:3 CACertificates:[] Certificates:[] SkipTLSVerify:false Headers:[] customTransport:<nil> tlsConfig:<nil>} KMSConfig:{Secrets:{URL: MasterKeyPath: MasterKeyString: masterKey:}} MFAConfig:{TOTP:[]} TelemetryConfig:{BindPort:0 BindAddress:127.0.0.1 EnableProfiler:false AuthUserFile: CertificateFile: CertificateKeyFile: TLSCipherSuites:[]} PluginsConfig:[] SMTPConfig:{Host: Port:25 From: User: Password:[redacted] AuthType:0 Encryption:0 Domain: TemplatesPath:templates}}"}
{"level":"info","time":"2022-05-02T08:32:22.519","sender":"kms","message":"secret provider registered for scheme: \"builtin\", encrypted status: \"AES-256-GCM\""}
{"level":"info","time":"2022-05-02T08:32:22.519","sender":"kms","message":"secret provider registered for scheme: \"local\", encrypted status: \"Secretbox\""}
{"level":"debug","time":"2022-05-02T08:32:22.519","sender":"plugins","message":"initialize"}
{"level":"debug","time":"2022-05-02T08:32:22.519","sender":"smtp","message":"configuration disabled, email capabilities will not be available"}
{"level":"debug","time":"2022-05-02T08:32:22.548","sender":"dataprovider_bolt","message":"bolt key store handle created"}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"service","message":"HTTP server not started, disabled in config file"}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"service","message":"FTP server not started, disabled in config file"}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"service","message":"WebDAV server not started, disabled in config file"}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"service","message":"telemetry server not started, disabled in config file"}
{"level":"debug","time":"2022-05-02T08:32:22.585","sender":"dataprovider_bolt","message":"delayed quota update loop started, wait time: 0s"}
{"level":"debug","time":"2022-05-02T08:32:22.585","sender":"dataprovider_bolt","message":"delayed quota update loop ended, wait time: 0s"}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"service","message":"initializing SFTP server with config {Banner:SFTPGo_2.2.2 Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] MaxAuthTries:0 Actions:{ExecuteOn:[] ExecuteSync:[] Hook:} HostKeys:[persist/id_rsa persist/id_ecdsa persist/id_ed25519] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveAuthentication:false KeyboardInteractiveHook: PasswordAuthentication:true FolderPrefix: certChecker:<nil> parsedUserCAKeys:[]}"}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"sftpd","message":"Loading private host key \"/var/azuracast/sftpgo/persist/id_rsa\""}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"sftpd","message":"Host key \"/var/azuracast/sftpgo/persist/id_rsa\" loaded, type \"ssh-rsa\", fingerprint \"SHA256:C6boCsUDkiOnX9dcRyQVvzaL7MBDOXpZHeVq2HTZcYs\""}
{"level":"info","time":"2022-05-02T08:32:22.585","sender":"sftpd","message":"Loading private host key \"/var/azuracast/sftpgo/persist/id_ecdsa\""}
{"level":"info","time":"2022-05-02T08:32:22.587","sender":"sftpd","message":"Host key \"/var/azuracast/sftpgo/persist/id_ecdsa\" loaded, type \"ecdsa-sha2-nistp521\", fingerprint \"SHA256:cB+ccDvhUy38ZzfEfi44bkixw/2iLvEWKrN8zs014P0\""}
{"level":"info","time":"2022-05-02T08:32:22.587","sender":"sftpd","message":"Loading private host key \"/var/azuracast/sftpgo/persist/id_ed25519\""}
{"level":"info","time":"2022-05-02T08:32:22.587","sender":"sftpd","message":"Host key \"/var/azuracast/sftpgo/persist/id_ed25519\" loaded, type \"ssh-ed25519\", fingerprint \"SHA256:eq5UF7YafR3lvfjIvywByu4DiW3xjSmjNjyy4tyeCC8\""}
{"level":"debug","time":"2022-05-02T08:32:22.587","sender":"sftpd","message":"enabled SSH commands [md5sum sha1sum cd pwd scp]"}
{"level":"info","time":"2022-05-02T08:32:22.587","sender":"sftpd","message":"server listener registered, address: [::]:2022"}
[2022-05-01T22:37:23.364533+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2022-05-01T22:42:24.552856+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2022-05-01T22:47:25.753488+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2022-05-01T22:52:26.940957+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2022-05-01T22:54:51.863893+00:00] AzuraCast.ERROR: HTTP client GET call to http://stations:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"Default"}}
[2022-05-01T22:54:51.865496+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 6: Could not resolve host: stations (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8000/admin/stats [] {"station":{"id":1,"name":"Default"}}
[2022-05-01T22:54:51.919561+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":1,"name":"Default"}}
```

**Comment by taz1685** [comment]
I was able to partially solve my problem by adding the icecast container (I originally thought it was builtin to the web image);
```
  stations:
    image: azuracast/azuracast_radio:0.15.2
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - icecast-data:/var/azuracast/servers/shoutcast2
      - azuracast-www_tmp:/var/azuracast/www_tmp
    networks:
      - backend
```
However the error message when trying to start the broadcaster or liquidsoap are as follows;
- _BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L251: Icecast is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help._
- _BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L251: Liquidsoap is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help._

**Comment by SlvrEagle23** [comment]
@taz1685 While I appreciate your desire to go it alone without our utility script, there's sincerely only about 4 files we ever put on the host filesystem, and they're all related specifically to orchestrating Docker and Docker Compose. Otherwise, the entirety of our operation takes place, as you would expect, within Docker containers, just as it would in your scenario. There is no disadvantage to using our helper scripts in this case.

Most important to note, we've switched in version 0.16.0 to a unified container that contains all of our dependencies in a single Docker image. That new Docker image is listed as `azuracast/azuracast` on both Docker Hub and the GH Container Registry. If you pull that version, it'll run on its own without any other cross-dependencies.

Beyond that, it's difficult for us to provide support for installations that try to set everything up by hand, as you've basically dismantled the best tool we have for making support easy across thousands of instances and tens of thousands of stations. I'd strongly recommend using our utility script to handle installation and updates.

**Comment by taz1685** [comment]
I can understand where you coming from and can appreciate its usecase. Looking at my usecase where im running a docker environment where the host system configuration and core file structure is immutable, having to run custom scripts there to maintain docker containers is not practicle, espically if looking to deploy across a cluster environment.

To your point around the 0.16.0 version, I just pulled it and it did run, however in the logs the following error keeps fireing;
- _ok: run: php-fpm: (pid 189) 17s
nginx: [emerg] cannot load certificate "/etc/nginx/certs/default.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/default.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)_

I am assuming this is a side affect of not using the install/deploy script?

**Comment by taz1685** [comment]
I managed to get 0.16.0 to work out as I needed in my environment. **_This is probabaly unsupported so YMMV_** but uses the generated output from the installation script I ran on another system.

### docker-compose.yml
```
services:
    web:
        container_name: azuracast
        image: ghcr.io/azuracast/azuracast:latest
        environment:
            LANG: en_US.UTF-8
            AZURACAST_DC_REVISION: 14
            AZURACAST_VERSION: latest
            AZURACAST_SFTP_PORT: 2022
            APPLICATION_ENV: production
            COMPOSER_PLUGIN_MODE: 'true'
            MYSQL_HOST: localhost
            MYSQL_PORT: 3306
            MYSQL_USER: azuracast
            MYSQL_PASSWORD: 9Qxr3rRtH7XN
            MYSQL_DATABASE: azuracast
            MARIADB_ROOT_PASSWORD: LLCAE3G6PxCqnLHrrPpk
            REDIS_HOST: localhost
            REDIS_PORT: 6379
            REDIS_DB: 1
            NGINX_TIMEOUT: 1800
            #LETSENCRYPT_HOST: 
            #LETSENCRYPT_EMAIL: 
            PUID: 1000
            PGID: 1000
        volumes:
            - letsencrypt:/etc/nginx/certs
            - letsencrypt_acme:/etc/acme.sh
            - www_uploads:/var/azuracast/uploads
            - station_data:/var/azuracast/stations
            - shoutcast2_install:/var/azuracast/servers/shoutcast2
            - geolite_install:/var/azuracast/geoip
            - sftpgo_data:/var/azuracast/sftpgo/persist
            - backups:/var/azuracast/backups
            - db_data:/var/lib/mysql
            - www_vendor:/var/azuracast/www/vendor
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            default:
                ipv4_address: 10.10.1.15

volumes:
  db_data:
    driver: local
  letsencrypt:
    driver: local
  letsencrypt_acme:
    driver: local
  shoutcast2_install:
    driver: local
  geolite_install:
    driver: local
  sftpgo_data:
    driver: local
  station_data:
    driver: local
  www_uploads:
    driver: local
  backups:
    driver: local
  www_vendor:
    driver: local
networks:
  default:
    external:
      name: DockerHostingNet
```
