### ISSUE TITLE
letsencrypt "No such service"

### ISSUE THREAD

**Issue by aldorr** [AzuraCast/AzuraCast#546]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 17.10

**Describe the issue in full detail, including screenshots if possible:**

After updating AzuraCast as described in the readme (especially because I wanted to add a letsencrypt cert), and then attempting the following command:
    `docker-compose run --rm letsencrypt certonly --webroot -w /var/www/letsencrypt`
I get the following error:
    `ERROR: No such service: letsencrypt`

I have restarted the system and have also done a manual update in the docker container, because of some issues I was having with a Bad Gateway. But now that seems to be fixed.

Do you have any recommendations for fixing the letsencrypt error?

Thanks a lot!

**Comment by SlvrEagle23** [comment]
@aldorr If it's been a while since you did so, update the contents of your `docker-compose.yml` file to more closely match the updated sample file here:

https://github.com/AzuraCast/AzuraCast/blob/master/docker-compose.sample.yml

Your copy of the file may be out of date and may not have the `letsencrypt` service registered.

**Comment by SlvrEagle23** [comment]
I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.

**Comment by aldorr** [comment]
Pardon my delay, and thanks for your help. I was able to update the docker-compose file and have now gained enough understanding of docker to feel silly for having asked this question in the first place.
Thanks also for closing this out.

**Comment by SlvrEagle23** [comment]
@aldorr No worries. Glad you were able to get things figured out. Hopefully AzuraCast continues to work well for you!

**Comment by oleoneto** [comment]
Running into this issue in version 5. `docker-compose.yml` matches the sample configuration referenced above: https://github.com/AzuraCast/AzuraCast/blob/master/docker-compose.sample.yml.

Command (from inside /var/azuracast/): 
`docker-compose run --rm letsencrypt renew --webroot -w /var/www/letsencrypt`

Error:
`ERROR: No such service: letsencrypt`

**Comment by oleoneto** [comment]
Providing an override may have just fixed it. Here's my configuration inside `docker-compose.override.yml`

```
version: '2.2'
 
services:
  letsencrypt:
    image: certbot/certbot
    command: /bin/true
    volumes:
      - nginx_letsencrypt_certs:/etc/letsencrypt
      - nginx_letsencrypt_www:/var/www/letsencrypt


volumes:
  nginx_letsencrypt_certs: {}
  nginx_letsencrypt_www: {}
```
