### ISSUE TITLE
Using a non-Let'sEncrypt Certificate

### ISSUE THREAD

**Issue by Smtgr14** [AzuraCast/AzuraCast#597]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04
**Describe the issue in full detail, including screenshots if possible:**
I am using the default docker install and I have a certificate from my domain provider, how do I go about using this certificate with AzuraCast? I'd rather not get one from Let's Encrypt since this has an annual expiration.

**Comment by SlvrEagle23** [comment]
@Smtgr14 You can use any SSL certificate you want, as long as you supply it to the `nginx` service as a mounted volume.

In the `docker-compose.yml` file, by default, the `nginx` service configuration looks like:

```yaml
  nginx:
    image: azuracast/azuracast_nginx:latest
    # ...
    volumes:
      - www_data:/var/azuracast/www
      - nginx_letsencrypt_certs:/etc/nginx/ssl
      - nginx_letsencrypt_www:/var/www/letsencrypt
    restart: always
```

You can modify that to point the SSL certificates to a file you have on the host computer by modifying the `volumes` section to look like:

```yaml
  nginx:
    image: azuracast/azuracast_nginx:latest
    # ...
    volumes:
      - www_data:/var/azuracast/www
      - /path/to/my_ssl_cert.crt:/etc/nginx/ssl/ssl.crt
      - /path/to/my_ssl_cert.key:/etc/nginx/ssl/ssl.key
    restart: always
```
