### ISSUE TITLE
SSL icecast error cors

### ISSUE THREAD

**Issue by Reaktiv4** [AzuraCast/AzuraCast#6104]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #919e3aa (2023-02-21 6:29)

### What happened?

New VPS installation. The certificate is installed and working, but the radio streams in icecast work on http.
Restarting and updating does not help.

As far as I understand the problem is that in the latest release of icecast the certificate and key must be in one file!!! And now they are in two files. The certificate is separate and the key is separate.
How can I fix the problem?

2) What is the full path in the system to the certificate and key? Where exactly are these files located on the system?

**Comment by Reaktiv4** [comment]
I reviewed all the files, I can’t find where the ssl files are located, I would manually make changes. Can anyone suggest?

**Comment by BusterNeece** [comment]
I can't reproduce this in my own instances. When I directly visit `radio-url:8000`, the SSL certificate works just fine there in its existing format, as a separate key/cert pair just like how nginx accepts it.

If you were looking to overwrite the certs we use, you would mount them using a `docker-compose.override.yml` file like this:

```yaml
services:
  web:
    volumes:
      - $PWD/your_ssl.crt/var/azuracast/acme/ssl.crt:ro
      - $PWD/your_ssl.key:/var/azuracast/acme/ssl.key:ro
```
