### ISSUE TITLE
Question: What about using default nginx from outside docker app

### ISSUE THREAD

**Issue by Ark74** [AzuraCast/AzuraCast#657]
Hi!
More than a bug, I would like to ask this,

Is it possible to stop nginx on the docker app and use the default nginx from the main server?
I've used the approach where the docker app will only listen a custom port and by setting the nginx conf file to the specific port of the app it will run without the need of two nginx fighting for default ports.

 I've looked at some closed bugs but cant fin anything on that direction.
Thanks!

**Comment by SlvrEagle23** [comment]
@Ark74 It's possible to have nginx on the host directly reference the `web` service running inside Docker, but I don't recommend it, because nginx itself not only needs to connect to PHP-FPM for the web application, but it also needs direct access to serve the static CSS/JS files that are part of the app.

If it was absolutely necessary, you could accomplish this by mounting the AzuraCast codebase development-style as a host-bound volume inside Docker, then exposing port 9000 directly to the host computer, like so:

```yaml
services:
  web:
    image: azuracast/azuracast_web:latest
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    ports:
      - "127.0.0.1:9000:9000"
    environment: &default-environment
      APPLICATION_ENV: "production" # "production" or "development"
      MYSQL_HOST: "mariadb"         # You can change this if you plan to connect to an external DB host.
      MYSQL_PORT: 3306              # ^
      MYSQL_USER: "azuracast"       # Once the database has been installed, don't change this.
      MYSQL_PASSWORD: "azur4c457"   # ^
      MYSQL_DATABASE: "azuracast"   # ^
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      AZURACAST_DC_REVISION: 2      # Only modified when this Docker Compose file has changed.
    volumes:
      - /some/local/host/path/AzuraCast:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
    init: true
    restart: always
```

You could then have nginx pass PHP calls to `localhost:9000` (which would go to the Docker container), but serve static files directly from the `/some/local/host/path/AzuraCast` folder.
