### ISSUE TITLE
Change Font for Public Pages

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#6800]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

779fdc0

### What happened?

I've attempted to modify the font for public pages using CSS in the Custom Branding menu. 
However, the default AC font is still being displayed.

Here's the code I've inserted in Custom CSS for Public Pages box:

link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css" rel="stylesheet" type="text/css" />

body {
    font-family: Vazirmatn, sans-serif;
}

**Comment by stardevelop** [comment]
<link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css" rel="stylesheet" type="text/css" />

**Comment by Moonbase59** [comment]
You used HTML in the CSS field—this doesn’t work.

You can use an `@import` instead:

```css
@import url('https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css');
body {
  font-family: Vazirmatn, sans-serif;
}
```

Or, if using Google fonts:
```css
@import url('https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100;200;300;400;500;600;700;800;900&display=swap');
body {
  font-family: Vazirmatn, sans-serif;
}
```
