### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by Partymann2000** [AzuraCast/AzuraCast#7299]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #203c228 

### What happened?

I use this for the SSL stuff

Using a Custom Certificate 
https://www.azuracast.com/docs/administration/ssl-and-lets-encrypt/

If I `docker-compose down` and then `docker-compose up -d` then the website is no longer accessible but if I remove the file and then restart everything works again

**Comment by Partymann2000** [comment]
This is my `docker-compose.override.yml`

```
services:
  web:
    volumes:
      - /etc/cloudflare/xenority.com/azuracast/ssl.crt:/var/azuracast/acme/ssl.crt:ro
      - /etc/cloudflare/xenority.com/azuracast/ssl.key:/var/azuracast/acme/ssl.key:ro
```
