### ISSUE TITLE
How to pipeline audio from docker container

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#732]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
HI, I am using the advanced custom configuration to pipeline audio outside of docker container.
How to reference an external process in the docker-composer as I do not want to 'break' anything in the installation ?

```
input = radio
process = pipe(process='/process/processor', input))
radio = process
```

BTW the above code does work perfectlty using 'traditional' method installer.

**Comment by CodeSteele** [comment]
You _should_ just be able to mount the pipe as a volume if I'm not mistaken:
https://forums.docker.com/t/socket-pipes-in-mounted-volumes-not-working/12861/7

https://docs.docker.com/compose/compose-file/#volumes

**Comment by SlvrEagle23** [comment]
@griffon56 This is more a question about Docker than a question about AzuraCast, but I can probably point you in the right direction.

In order to communicate outside the `stations` container, you'll have to either communicate over TCP/IP or mount a volume into the container that contains files that are shared, either between the host and the container or between multiple containers.

In this case, you can add the socket you're trying to connect to as a volume, by updating your `docker-compose.yml` file to specify a new volume in the `stations` service, like so:

```yaml
  stations:
    ports:
     - '8090:8090'
     - ...
     - '8096:8096'
    volumes:
     - /process/processor:/process/processor
     - station_data:/var/azuracast/stations
     - nginx_letsencrypt_certs:/etc/nginx/ssl:ro
```
