### ISSUE TITLE
webserver and azuracast

### ISSUE THREAD

**Issue by ElNadie** [AzuraCast/AzuraCast#733]
Good evening 
I have a question can i have webserver and azuracat together? how can i change azuracast ports from 80 to an other port.. I have see the documentetion but i can not understand how. Can you explain me step by step, its not simply for azuracast team but i have this question

**Comment by impli-osx** [comment]
Hi,

If you have a docker install, you can have azuracast and a webserver on the same server. But you should modify the port (80 & 443 are the webserver defautl ports).

You can change the ports in the docker-compose.yml file (you can find this in your azuracast install directory).

Here, the section in docker-compose.yml


```
  nginx:
    image: azuracast/azuracast_nginx:latest
    ports:
      - '81:80'
      - '444:443'
    depends_on:
      - web
      - stations
    volumes:
      - www_data:/var/azuracast/www
      - nginx_letsencrypt_certs:/etc/nginx/ssl
      - nginx_letsencrypt_www:/var/www/letsencrypt
    restart: always
```

In this example, the SSL port (443) is redirect to 444 and the non-SSL port (80) is redirect to 81.
So, after this modification, you should have to use URLs like https://www.example.com:444 or http://www.example.com:81
And http://www.example.com send the user on your classical webserver (Apache/nginx/...)
