### ISSUE TITLE
Failed to start MariaDB using docker compose

### ISSUE THREAD

**Issue by scob7** [AzuraCast/AzuraCast#7641]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release

### What happened?

Trying to install on Ubuntu 22.04.5 LTS with existing docker instance. MariaDB does not successfully start and keeps respawning with the following error:

`Fatal error: Can't open and lock privilege tables: Table 'mysql.db' doesn't exist`

### Relevant log output

```shell
azuracast          | ** Running startup script '/etc/my_init.d/00_disable_mariadb.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/00_disable_redis.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/00_setup_user.sh'...
azuracast          | usermod: no changes
azuracast          | Docker 'azuracast' User UID: 1024
azuracast          | Docker 'azuracast' User GID: 65536
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/01_self_signed_ssl.sh'...
azuracast          | Generating self-signed certificate...
azuracast          | ..+.....+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.+.....+...+......+.......+..+.+......+...+...+..+......+.+...+........+...+..........+..+....+.........+..+...+..........+..+.......+.....+............+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.+..+....+...+............+.........+......+...+.....+.....................+....+......+..+.......+.....+.......+.....................+.........+.....+.+...+..+...+....+........+...+.......+...+..+...+....+..+..........+........+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
azuracast          | .....+........+...+...+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+............+..+.+...+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+....+...............+...+......+..............+.+.........+........+.............+..............+.+.........+..+....+..+..........+..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
azuracast          | -----
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/02_install_extra_packages.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/03_persist_dir.sh'...
azuracast          | Creating persist directories...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/04_mariadb_conf.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/05_centrifugo_conf.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/05_nginx_conf.sh'...
azuracast          | ln: failed to create symbolic link '/etc/nginx/sites-enabled/default.vhost': File exists
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/05_setup_db.sh'...
azuracast          | 2024-12-29 00:39:40+00:00 [Note] [Entrypoint]: Initial DB setup...
azuracast          | 2024-12-29 00:39:41+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
azuracast          | 2024-12-29 00:39:41+00:00 [Note] [Entrypoint]: Initial DB setup...
azuracast_updater  | time="2024-12-29T00:39:41Z" level=debug msg="Making sure everything is sane before starting"
azuracast_updater  | time="2024-12-29T00:39:41Z" level=debug msg="Retrieving running containers"
azuracast_updater  | time="2024-12-29T00:39:41Z" level=debug msg="There are no additional watchtower containers"
azuracast_updater  | time="2024-12-29T00:39:41Z" level=info msg="Watchtower 1.5.1"
azuracast_updater  | time="2024-12-29T00:39:41Z" level=info msg="Using no notifications"
azuracast_updater  | time="2024-12-29T00:39:41Z" level=info msg="Only checking containers in scope \"azuracast\""
azuracast_updater  | time="2024-12-29T00:39:41Z" level=info msg="Periodic runs are not enabled."
azuracast_updater  | time="2024-12-29T00:39:41Z" level=info msg="The HTTP API is enabled at :8080."
azuracast          | 2024-12-29 00:39:41+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
azuracast          |    You need to specify one of MARIADB_ROOT_PASSWORD, MARIADB_ROOT_PASSWORD_HASH, MARIADB_ALLOW_EMPTY_ROOT_PASSWORD and MARIADB_RANDOM_ROOT_PASSWORD
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/06_php_conf.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/07_sftpgo_conf.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running startup script '/etc/my_init.d/10_clear_temp.sh'...
azuracast          | ** Startup script complete.
azuracast          | ** Running Supervisord...
azuracast          | 2024-12-29 00:39:41,918 WARN No file matches via include "/var/azuracast/stations/*/config/supervisord.conf"
azuracast          | 2024-12-29 00:39:41,918 INFO Included extra file "/etc/supervisor/supervisord.conf" during parsing
azuracast          | 2024-12-29 00:39:41,918 INFO Included extra file "/etc/supervisor/minimal.conf.d/mariadb.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/minimal.conf.d/redis.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/full.conf.d/centrifugo.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/full.conf.d/cron.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/full.conf.d/nginx.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/full.conf.d/php-fpm.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/full.conf.d/php-nowplaying.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/full.conf.d/php-worker.conf" during parsing
azuracast          | 2024-12-29 00:39:41,919 INFO Included extra file "/etc/supervisor/full.conf.d/sftpgo.conf" during parsing
azuracast          | 2024-12-29 00:39:41,920 INFO Included extra file "/etc/supervisor/full.conf.d/startup.conf" during parsing
azuracast          | 2024-12-29 00:39:41,920 INFO Set uid to user 0 succeeded
azuracast          | 2024-12-29 00:39:41,925 INFO RPC interface 'supervisor' initialized
azuracast          | 2024-12-29 00:39:41,925 CRIT Server 'unix_http_server' running without any HTTP authentication checking
azuracast          | 2024-12-29 00:39:41,925 INFO supervisord started with pid 7
azuracast          | 2024-12-29 00:39:42,929 INFO spawned: 'stdout' with pid 118
azuracast          | 2024-12-29 00:39:42,932 INFO spawned: 'mariadb' with pid 119
azuracast          | 2024-12-29 00:39:42,935 INFO spawned: 'redis' with pid 120
azuracast          | 2024-12-29 00:39:42,939 INFO spawned: 'startup' with pid 121
azuracast          | 
azuracast          | Waiting for cache service (Redis) to become available...
azuracast          | ========================================================
azuracast          | 
azuracast          |  [OK] Services started up and ready!                                            
azuracast          | 
azuracast          | 
azuracast          | Waiting for database (MariaDB) to become available...
azuracast          | =====================================================
azuracast          | 
azuracast          | 2024-12-29 00:39:44,186 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
azuracast          | 2024-12-29 00:39:44,186 INFO success: mariadb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
azuracast          | 2024-12-29 00:39:44,186 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
azuracast          | 2024-12-29 00:39:44,186 INFO success: startup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
🖥️🎵－🎶－📻 Waiting...redis stdout | 120:C 29 Dec 2024 00:39:42.964 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
azuracast          | redis stdout | 
azuracast          | redis stdout | 120:C 29 Dec 2024 00:39:42.964 * oO0OoO0OoO0Oo Redict is starting oO0OoO0OoO0Oo
azuracast          | redis stdout | 120:C 29 Dec 2024 00:39:42.964 * Redict version=7.3.0, bits=64, commit=00000000, modified=1, pid=120, just started
azuracast          | redis stdout | 120:C 29 Dec 2024 00:39:42.964 * Configuration loaded
azuracast          | redis stdout | 
azuracast          | redis stdout | 120:M 29 Dec 2024 00:39:42.965 * monotonic clock: POSIX clock_gettime
azuracast          | redis stdout | 
azuracast          | redis stdout | 120:M 29 Dec 2024 00:39:42.966 * Running mode=standalone, port=6379.
azuracast          | redis stdout | 
azuracast          | redis stdout | 120:M 29 Dec 2024 00:39:42.967 * Server initialized
azuracast          | redis stdout | 
azuracast          | redis stdout | 120:M 29 Dec 2024 00:39:42.967 * Ready to accept connections tcp
azuracast          | redis stdout | 120:M 29 Dec 2024 00:39:42.967 * Ready to accept connections unix
azuracast          | redis stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:42 0 [Note] Starting MariaDB 11.4.4-MariaDB-deb12 source revision e9a502df08bad16aa8a354e854f3c014b1380e32 server_uid zzaGlFJj5zfmotX9uozp4Xgs9EI= as process 119
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Number of transaction pools: 1
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Completed initialization of buffer pool
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Buffered log writes (block size=512 bytes)
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: End of log at LSN=37792
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Opened 3 undo tablespaces
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: log sequence number 37792; transaction id 4
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] Plugin 'FEEDBACK' is disabled.
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] Plugin 'wsrep-provider' is disabled.
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [Note] InnoDB: Buffer pool(s) load completed at 241229  0:39:43
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:43 0 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:46 0 [Note] Server socket created on IP: '0.0.0.0'.
azuracast          | mariadb stdout | 2024-12-29  0:39:46 0 [Note] Server socket created on IP: '::'.
azuracast          | mariadb stdout | 
azuracast          | mariadb stdout | 2024-12-29  0:39:46 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.db' doesn't exist
azuracast          | mariadb stdout | 2024-12-29  0:39:46 0 [ERROR] Aborting
azuracast          | mariadb stdout | 
azuracast          | 2024-12-29 00:39:47,108 WARN exited: mariadb (exit status 1; not expected)
🖥️－🎵－🎶📻 Waiting...2024-12-29 00:39:47,198 INFO spawned: 'mariadb' with pid 151
```

**Comment by scob7** [comment]
And here is my docker compose file.

```
services:
  web:
    container_name: azuracast
    image: "ghcr.io/azuracast/azuracast:latest"
    labels:
      - "com.centurylinklabs.watchtower.scope=azuracast"
    # Want to customize the HTTP/S ports? Follow the instructions here:
    # https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports
    ports:
      - '8880:8880'
      - '8443:8443'
      - '2022:2022'
      - '10000:10999'
    environment:
      #- AZURACAST_PUID=1024
      - AZURACAST_PGID=65536
      - AUTO_ASSIGN_PORT_MIN=10000
      - AUTO_ASSIGN_PORT_MAX=10999
      - AZURACAST_HTTP_PORT=8880
      - AZURACAST_HTTPS_PORT=8443
    volumes:
      - station_data:/var/azuracast/stations
      - backups:/var/azuracast/backups
      - db_data:/var/lib/mysql
      - www_uploads:/var/azuracast/storage/uploads
      - shoutcast2_install:/var/azuracast/storage/shoutcast2
      - stereo_tool_install:/var/azuracast/storage/stereo_tool
      - geolite_install:/var/azuracast/storage/geoip
      - sftpgo_data:/var/azuracast/storage/sftpgo
      - acme:/var/azuracast/storage/acme
      - /mnt/nas-media/Music:/var/azuracast/stations/defaultradio/media
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-size: "1m"
        max-file: "5"

  updater:
    container_name: azuracast_updater
    image: ghcr.io/azuracast/updater:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "1m"
        max-file: "5"

volumes:
  db_data:
  acme:
  shoutcast2_install:
  stereo_tool_install:
  geolite_install:
  sftpgo_data:
  station_data:
  www_uploads:
  backups:
```
