### ISSUE TITLE
SSL not working in Azuracast - certbot and override.yml

### ISSUE THREAD

**Issue by s7ntax** [AzuraCast/AzuraCast#7820]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Powered by AzuraCast • v0.21.0 Stable • Docker • PHP 8.4

### What happened?

Since updating the sites SSL certs using certbot, azuracast no longer has functioning ssl.

```
docker-compose.override.yml

version: '2.2'

services:
      web:
        volumes:
            - /var/www/arpradio.com/mp3/error.mp3
            - /etc/letsencrypt/live/arpradio.com/fullchain.pem:/var/azuracast/acme/ssl.crt:ro
            - /etc/letsencrypt/live/arpradio.com/privkey.pem:/var/azuracast/acme/ssl.key:ro
```

### Relevant log output

```shell

```
