### ISSUE TITLE
Loading music files from external directory /Different FTP or storage service as google Drive/

### ISSUE THREAD

**Issue by Pjotr9** [AzuraCast/AzuraCast#864]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Probably built-in SFTP client with possibility to connect "outside" of Docker where I am running AzuraCast. Why? Well, I already have different FTP with +500GB of music with great price for used storage. 

**Describe alternatives you've considered**
I considered option of loading my music library from cloud storage as Google Drive or Dropbox, however I am not sure how open these services are for browsing folders/files stored there from this type of app (Maybe their API allows this? Not sure). Ultimately, there could be just option to add song manually, so I would just copy/paste song's direct URL.

**Additional context**
Sorry if there is such a option. I just haven't found it :)
Thanks and have a nice day

**Comment by muzo178** [comment]
You could always mount your external ftp with a variety of tools. If your ftp allows smb connections you could mount it with fstab. Or try curlftpfs. Not sure how healthy this would be but it is worth a shot.

**Comment by MyTheValentinus** [comment]
Hello,
In my case i added SFTP mount to my docker stack.
Like this:
```
  sftp:
    image: atmoz/sftp
    restart: always
    volumes:
        - /path/or/volume/to/stations/files/STATION_NAME/:/home/USER/radio/
    ports:
        - "23:22"
    command: USER:PASSWORD:1000
```
